### ISSUE TITLE
Clarification note for picking hash vs append distribution

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#115]
I'm capturing @umurc's note in the internal email thread (re: Hash vs append distribution) in this issue. @umurc brought this up as a semi-related issue as part of our discussion on #95.

Related to this thread but as a separate item, I'm noting the current explanation for append might also impact its usage: "Append distributed tables are best suited to append-only event data which arrives in a time-ordered series." --> users might relate to this and pick this method, without considering/being aware of its broader implications.

**Comment by begriffs** [comment]
Closing this due to newly created #135 and our desire to promote the multi-tenant and analytics use cases.
