### ISSUE TITLE
Document support for DDL propagation (ALTER, etc.)

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#120]
Mentioned in #18 as well

**Comment by lfittl** [comment]
As an additional note from our lunch conversation today:

We should also aim to document locking requirements, and whether we execute a given DDL command in parallel or serial.

Essentially, the answer most customers will want answered is "Do I need to schedule downtime?" when an application developer makes a data model change through e.g. a Rails migration.

https://www.braintreepayments.com/blog/safe-operations-for-high-volume-postgresql/ is a good reference on how to think about this.
