### ISSUE TITLE
Update docs for new or modified UDFs

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#128]
CItus issues for the 5.2 milestone involve these **undocumented** UDFs. Do we want to document any?

```
Schema              | pg_catalog
Name                | worker_fetch_regular_table
Result data type    | void
Argument data types | text, bigint, text[], integer[]
Type                | normal

Schema              | pg_catalog
Name                | master_modify_multiple_shards
Result data type    | integer
Argument data types | text
Type                | normal

Schema              | pg_catalog
Name                | master_update_shard_statistics
Result data type    | bigint
Argument data types | shard_id bigint
Type                | normal

This one got a third parameter:

Schema              | pg_catalog
Name                | worker_apply_shard_ddl_command
Result data type    | void
Argument data types | bigint, text, text
Type                | normal
```

All of the UDFs **documented** in `reference/user_defined_functions.rst` have the same signatures in  5.2 as in 5.1. What has changed is that they now support schema-qualified table names.

I am unable to verify whether the signatures of `rebalance_table_shards` or `replicate_table_shards` have changed.

I inspected the UDFs using Citus built from master and identifying itself as 5.2-1

**Comment by sumedhpathak** [comment]
@begriffs We should have already document ``master_modify_multiple_shards`` in our docs master branch?

**Comment by begriffs** [comment]
You're right, the crappy sphinx search doesn't show it but grep does. I grepped for the the others and verified they are not present though.
