### ISSUE TITLE
Add question about unique constraints to faq

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#131]
This is from our slack room:

> ERROR:  cannot distribute relation: "foo"
> DETAIL:  Distributed relations cannot have UNIQUE constraints or PRIMARY KEYs that do not include the partition column. 
> what does this error mean?

@craigkerstiens says it's a common question, so add it to the FAQ.

**Comment by saicitus** [comment]
@begriffs : You could use the following for reference:
Currently Citus imposes primary key constraint only if the distribution column is a part of the primary key. To elaborate if only a single column constitutes the primary key then the distribution key has to be that column and if more than one column constitute the primary key, the distribution key should be any one of those columns. 
This assures that the constraint needs to be checked only on one shard(the shard where the insert happens) to ensure uniqueness.

**Comment by jmunsch** [comment]
follow up question, is there an example of what this would look like? Did I miss something?


```
2017-05-23 14:54:04,302 INFO  [3859][sqlalchemy.engine.base.Engine] 
CREATE TABLE bowie_partition.host (
	rowid SERIAL NOT NULL, 
	host VARCHAR NOT NULL, 
	num_todo INTEGER DEFAULT '0' NOT NULL, 
	num_urls INTEGER DEFAULT '0' NOT NULL, 
	PRIMARY KEY (rowid), 
	UNIQUE (rowid), 
	UNIQUE (host)
)```

Given the following two attempts i get the same error:

```
SELECT create_distributed_table('bowie_partition.host', 'host');
SELECT create_distributed_table('bowie_partition.host', 'rowid');
```

error:


``` Distributed relations cannot have UNIQUE, EXCLUDE, or PRIMARY KEY  constraints that do not include the partition column (with an equality operator if EXCLUDE).```

I tried searching slack ... but it appears any questions related directly to the error are no longer a part of the 10,000 message limit.
