### ISSUE TITLE
Simplify docker instructions for Mac

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#138]
Docker is better integrated nowadays

**Comment by lfittl** [comment]
Bumping this one, since we just had a customer install docker machine instead of Docker on OSX, based on our (outdated) instructions.

We really should add a pointer to https://docs.docker.com/engine/installation/mac/ in https://docs.citusdata.com/en/v6.0/installation/single_machine_docker.html

**Comment by lfittl** [comment]
@begriffs PR looks good.
