### ISSUE TITLE
Multi-machine config docs: Which machines in the worker list?

### ISSUE THREAD

**Issue by kmatt** [citusdata/citus_docs#141]
https://github.com/citusdata/citus_docs/blob/v5.1/installation/production_rhel.rst

**Steps to be executed on the master node
1. Add worker node information**

Should this list include the master node, or only the workers?

Docs are unclear if the master machine is also a worker.

**Comment by begriffs** [comment]
Verified that this ambiguity is still present - https://docs.citusdata.com/en/v7.3/installation/production_rhel.html#steps-to-be-executed-on-the-coordinator-node

We can add a note that the coordinator is not itself a worker and shouldn't be included in master_add_node.
