### ISSUE TITLE
Add "Use Cases" to About Citus section

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#143]
Exact name is TBD, could be Use Cases or How To Use. In any case it will describe the general features of multi-tenant vs realtime analytics uses as well as the pros and cons of each.

* Multi-tenant
  * (+) SQL Coverage
  * (+) Ease of Migration
  * (–) No Parallelism
  * (–) Less effective for large (or few) tenants
* Analytics
  * (+) Parallelism
  * (+) Linear Scalability
  * (–) Reduced SQL Coverage
  * (–) Upfront Data Modeling

**Comment by sumedhpathak** [comment]
To clarify, it involves modifying or amending this section:
https://docs.citusdata.com/en/v5.2/aboutcitus/what_is_citus.html#when-to-use-citus
