### ISSUE TITLE
Add Multi-Tenant/SaaS tutorial

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#144]
Our primary goal with tutorials is to quickly show users how Citus works on a single node and make them successful.

A secondary goal is to prime users for different workloads where Citus is applicable.

We probably want to have a second tutorial, one that has hash distribution on tenant_id, to prime users on multi-tenant apps.

**Comment by samay-sharma** [comment]
@ozgune , Closing this issue as we merged #291
