### ISSUE TITLE
DDL propagation support (Create index, alter table)

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#159]
This recently came up in our Slack channel. I'm copy/pasting the conversation below.

brian.freeman.slate [7:48 PM]  If I issue a `DROP INDEX` on the master node, does that propagate to all the workers? if not, how do I drop an index on a distributed table?

brian.freeman.slate [7:53 PM]  According to the docs: Currently `CREATE INDEX` and `ALTER TABLE` are the only DDL changes that Citus propagates automatically.
This is from http://docs.citusdata.com/en/v5.2/reference/configuration.html?highlight=index#citus-enable-ddl-propagation-boolean

scott [7:58 PM]  pretty sure drop table does too

robin.thomas [7:58 PM]  https://github.com/citusdata/citus/blob/v5.2.0/src/test/regress/sql/multi_index_statements.sql#L26

**Comment by sumedhpathak** [comment]
To Do: Get list of supported commands.

https://github.com/citusdata/citus/issues/1080 and https://github.com/citusdata/citus/issues/633 are related issues coming up in 6.2
