### ISSUE TITLE
Change code blocks of rollup function in real time dashboard reference

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus_docs#160]
In real-time dashboard reference architecture, we have some modifications in rollup function throughout the text. Currently we only write small example query which should be added to rollup function by user. I think instead of writing the part we need to add, we should write full rollup function. My observation is merging old function and new additions is not trivial and we should provide already merged version or at least something like;

``` sql
CREATE FUNCTION rollup_1min(p_source_shard text, p_dest_shard text) RETURNS void
AS $$
BEGIN
...
-- new additions etc.
...
END;
$$ LANGUAGE 'plpgsql';
```

I believe, this kind of code block would be more clear to reader, but this is just my opinion. This suggestion is open to discussion.

**Comment by begriffs** [comment]
The new version of the guide uses the `http_request_1min` function. We now show a working diff for each necessary change. I think it reads pretty clearly now, so closing this issue. But if you disagree feel free to re-open it.
