### ISSUE TITLE
expire_old_request_data function gives error in real time dashboard reference

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus_docs#161]
This function calls master_modify_multiple_shards UDF which uses transactions. However as far as I understand, we cannot use UDF which uses transactions in another functions. Calling expire_old_request_data returns this error message;

``` sql
ERROR: COMMIT is not allowed in a SQL function
CONTEXT: SQL function "expire_old_request_data" during startup
```

Content of expire_old_request_data function;

``` sql
-- another function for the master
CREATE FUNCTION expire_old_request_data() RETURNS void
AS $$
  SET LOCAL citus.all_modification_commutative TO TRUE;
  SELECT master_modify_multiple_shards(
    'DELETE FROM http_request WHERE ingest_time < now() - interval ''1 day'';');
  SELECT master_modify_multiple_shards(
    'DELETE FROM http_request_1min WHERE ingest_time < now() - interval ''1 month'';');
END;
$$ LANGUAGE 'sql';
```

**Comment by marcocitus** [comment]
This seems to be a syntactic issue, should be:

    CREATE FUNCTION expire_old_request_data() RETURNS void
    AS $$
    BEGIN
      SET LOCAL citus.all_modification_commutative TO TRUE;
      SELECT master_modify_multiple_shards(
        'DELETE FROM http_request WHERE ingest_time < now() - interval ''1 day''');
      SELECT master_modify_multiple_shards(
        'DELETE FROM http_request_1min WHERE ingest_time < now() - interval ''1 month''');
    END;
    $$ LANGUAGE 'plpgsql';

**Comment by lithp** [comment]
If you want to keep using the `sql` lang the problem is actually the `END;` at the bottom of the function, removing that fixes it.

**Comment by begriffs** [comment]
Thankfully this complicated stuff is no longer needed in the guide and regular delete statements suffice.
