### ISSUE TITLE
What should our canonical colocation diagram be?

### ISSUE THREAD

**Issue by lithp** [citusdata/citus_docs#165]
We curently have two different image which stress different representations.

The first image focuses exclusively on the idea that items with the same distribution key will be placed onto the same machine but ignores the idea of shards:

![colocation](https://cloud.githubusercontent.com/assets/466333/18249171/4d5802ea-7385-11e6-80a2-5110e51cd16c.png)

The second focuses exclusively on, I guess "virtual shards", and how rows with the same distribution key will be placed on the same "shard" (which looks like it's just a machine).

![shard_tenant](https://cloud.githubusercontent.com/assets/466333/18249198/6e6ed0bc-7385-11e6-82a8-09a4bc1c097b.png)
- Should there be a canonical representation we use to visually show colocation?
- If so, and given that we definitely want to visually show that rows with the same distribution key will be placed onto the same machine, do we also want to include the concept of shards into the diagram?

**Comment by begriffs** [comment]
The "Technical Solution" page uses the first image. Does that mean this issue was decided?

**Comment by lithp** [comment]
I think unless @ozgune has any objections this can be closed

**Comment by ozgune** [comment]
I meant that we should probably pick one of those representations and use it consistently in our docs and blog. Since we use both representations right now, I'm inclined to keep this issue open.
