### ISSUE TITLE
Change API for worker roll-ups

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus_docs#169]
Currently we have a function named `rollup_1min()`. It'd be more generic if we provide an API such as `rollup(period=1min)`. In this case, the users could easily generate rollups for different periods.

**Comment by begriffs** [comment]
Thew new `rollup_http_request` function in the guide also hardcodes one minute. We could pretty easily modify it to accept a `period` argument. Might make it slightly more complicated and obscure the other things people are learning in the guide. Think we should do that, or should I close this issue?

**Comment by begriffs** [comment]
We no longer use a function to do this in the guide, we use insert-select.
