### ISSUE TITLE
Document master_expire_table_cache UDF

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus_docs#172]
We are introducing a new UDF master_expire_table_cache(tableName) in the new version.

This function accepts a distributed table name, and drops its shards cached copies from all workers.

It works only for **small** tables meaning tables with less number shards than `citus.large_table_shard_count` aka broadcast tables. The function fails if it is called on a regular table, or a distributed table with many shards.

**Comment by begriffs** [comment]
Confirmed that the UDF is still missing from docs.

**Comment by marcocitus** [comment]
I don't think it's worth adding. I think it'll be removed from 7.4.
