### ISSUE TITLE
FQA - How do I change the shard count for a hash partitioned table?

### ISSUE THREAD

**Issue by EamonZhang** [citusdata/citus_docs#181]
https://docs.citusdata.com/en/v5.2/faq/faq.html

What's the differents between 

How do I change the shard count for a hash partitioned table?
and 
How do I choose the shard count when I hash-partition my data?

**Comment by sumedhpathak** [comment]
@EamonZhang Thanks for the note. One question is intended to address changing the shard count for an *already sharded* table. E.g. Someone started with 32 shards, but wants to re-partition to 64 shards.
The other question is intended to address what is a good count to begin with. I agree the answer to the former isn't very informative. Will open up a new issue to update that. Thanks!
