### ISSUE TITLE
Update FAQ Entry for changing shard count for already sharded table

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#182]
For FAQ Question:https://docs.citusdata.com/en/v5.2/faq/faq.html#how-do-i-change-the-shard-count-for-a-hash-partitioned-table.

We currently have the same answer as that of: https://docs.citusdata.com/en/v5.2/faq/faq.html#how-do-i-choose-the-shard-count-when-i-hash-partition-my-data

We should update the first one to note options on how to re-split shards, and potential future improvements.

**Comment by begriffs** [comment]
"Change" and "choose" now have different text. However "change" is very short and still probably needs more detail than "contact us."
