### ISSUE TITLE
Consider publishing docs for the development version

### ISSUE THREAD

**Issue by lithp** [citusdata/citus_docs#186]
Since we're open source people can run Citus off of master (although we don't recommend it!), but they aren't able to read anything about the changes until we publish new docs while we cut a release.

Postgres has a section of the docs just for the development versino: https://www.postgresql.org/docs/devel/static/index.html

We could do the same thing here: http://docs.citusdata.com/en/v5.2/index.html

**Comment by begriffs** [comment]
In RTD (Read The Docs) parlance that would be the version called `latest` which tracks the master branch of docs. However our instance of RTD (https://readthedocs.org/projects/citus-docs/) is misbehaving and the latest version is stuck on an old commit. We can write to them for support on this issue if desired.

**Comment by lithp** [comment]
Oh wow, it's stuck at September 2nd! I can try playing around with it a bit, any chance you can give my user admin rights? My username is `lithp` over there too.

**Comment by begriffs** [comment]
Sure, just added you as a maintainer.

**Comment by lithp** [comment]
Thanks! Some aimless clicking seems to have solved the problem and it now builds the right version, but for some reason `latest` now redirects to `v5.1`. baby steps...

**Comment by begriffs** [comment]
I believe that redirect is happening because of a Cloudflare rule. @craigkerstiens can remove it.

**Comment by begriffs** [comment]
The redirect is gone now and the `latest` version is available for viewing.
