### ISSUE TITLE
Non-existent file is referenced by scaling_data_injestion

### ISSUE THREAD

**Issue by lithp** [citusdata/citus_docs#187]
We're asked to COPY a file which we're never provided: `psql -c "\COPY counters FROM 'counters-20160304.csv' (FORMAT CSV)"`

(edited to include the correct url)

https://docs.citusdata.com/en/v6.0/performance/scaling_data_ingestion.html

In fact, this page has lots of references to files which don't exist, making it difficult to follow along.

**Comment by begriffs** [comment]
Our benchmarking steps have all changed and use pgbench scripts to populate tables rather than telling the user to download data files.
