### ISSUE TITLE
Reference Architecture returns a few errors

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus_docs#206]
I ran into a few errors while I was testing the reference architecture for the v6.0 docs. 

A few examples:-

* `SELECT expire_old_request_data()` returns
```sql
ERROR:  COMMIT is not allowed in a SQL function
CONTEXT:  SQL function "expire_old_request_data" during startup
```
* Errors in the CREATE AGGREGATE function
``` 
CREATE AGGREGATE sum (hll)
(
  sfunc = hll_union_agg,
  stype = internal,
);
```

sfunc should be a function and there is an extra , after stype.

* A couple of queries refer to minute, however there isn't a minute column in the `http_request_1min` table.

We should have a look at these errors and fix them.

**Comment by lithp** [comment]
All of these are fixed and pushed to master.
