### ISSUE TITLE
Creation of reference table fails

### ISSUE THREAD

**Issue by HackerMD** [citusdata/citus_docs#209]
When trying to distribute a reference table

```sql
select create_reference_table('my_table');
```

I get the following error:

```
ERROR:  cannot distribute relation: "my_table"
DETAIL:  Distributed relations cannot have UNIQUE, EXCLUDE, or PRIMARY KEY constraints that do not include the partition column (with an equality operator if EXCLUDE).
```

What is the partition column?

**Comment by onderkalaci** [comment]
Hi @HackerMD, 

By default, the first column is considered to be the partition column for reference tables. So, if you have a unique key which includes the first column of the table, you shouldn't see this error. Does that help for your case?

We're going to have a more comprehensive reference table support in the next release with [#879](https://github.com/citusdata/citus/issues/879) where reference tables wouldn't actually need a partition column. Thus, we're considering to allow unique keys for any column on the upcoming release, and following the issue on citus repo [#715](https://github.com/citusdata/citus/issues/715).

**Comment by HackerMD** [comment]
Thanks! Adding the first column to the UNIQUE constraint did the trick.

Why not using the column with PRIMARY KEY constraint (in case there is such a column) as default partition column rather than simply taking the first column? This would simplify things in my opinion, since the column order may be hard to control, e.g. when using object relational mapper classes with inheritance and mixins.

**Comment by HackerMD** [comment]
I ran into a related issue with the next table:

```sql
CREATE TABLE my_table (
	id SERIAL NOT NULL,
	name VARCHAR,
	PRIMARY KEY (id),
	UNIQUE (name, id),
);
SELECT create_reference_table('my_table');

CREATE TABLE my_second_table (
	id SERIAL NOT NULL,
	name VARCHAR,
	PRIMARY KEY (id),
	UNIQUE (name, my_table_id, id),
	FOREIGN KEY(my_table_id) REFERENCES my_table (id) ON DELETE CASCADE
);
SELECT create_reference_table('my_second_table');
```

```
ERROR:  cannot create foreign key constraint
DETAIL:  Partition column must exist both referencing and referenced side of the foreign constraint statement and it must be in the same ordinal in both sides.
```

**Can one reference table _reference_ another?**

When I instead try to distribute `my_second_table`

```sql
SELECT create_distributed_table('my_second_table', 'id');
```

I get the following error:

```
ERROR:  cannot create foreign key constraint
DETAIL:  Foreign key constraint can only be created on co-located tables.
```

**Can a distributed table _reference_ a reference table?**

**Comment by HackerMD** [comment]
Given the following schema:

```sql
CREATE TABLE my_table (
    id SERIAL NOT NULL,
    name VARCHAR,
    PRIMARY KEY (id),
    UNIQUE (name, id)
);

CREATE TABLE my_second_table (
    my_table_id SERIAL NOT NULL,
    id SERIAL NOT NULL,
    name VARCHAR,
    PRIMARY KEY (my_table_id, id),
    UNIQUE (name, my_table_id, id),
    FOREIGN KEY(my_table_id) REFERENCES my_table (id) ON DELETE CASCADE
);
```

This works

```sql
SET citus.shard_replication_factor = 10;
SELECT create_distributed_table('my_table', 'id');
SELECT create_distributed_table('my_second_table', 'my_table_id');
```

this works, too:

```sql
SET citus.shard_replication_factor = 1;
SELECT create_reference_table('my_table');
SELECT create_reference_table('my_second_table');
```

but this doesn't:

```sql
SET citus.shard_replication_factor = 10;
SELECT create_reference_table('my_table');
SELECT create_reference_table('my_second_table');
```

So it seems there is currently no way to define a  FOREIGN KEY constraint for a "replicated" reference table, i.e. a table that exists on each node and can be used for a JOIN with a distributed table as described in the [docs](https://docs.citusdata.com/en/stable/reference/sql_workarounds.html#join-a-local-and-a-distributed-table)?

**Comment by sumedhpathak** [comment]
@HackerMD I added this example to this issue in our Citus repo: https://github.com/citusdata/citus/issues/968. 
That ticket in our Citus repo captures implementation of Foreign Keys with reference tables, and is currently not slated for our 6.1 release.

The following issue: https://github.com/citusdata/citus/issues/879 is a top-level tracking issue for proper reference table implementation, and captures all the current open issues.

Since these are product and not documentation issues, feel free to comment or open issues in our main Citus repo.

Finally, are you looking to use Citus with a particular use-case in mind? Thanks!

**Comment by HackerMD** [comment]
Hi @sumedhpathak!

Thanks for your feedback! I'm looking forward to further development in this direction.

I'm using _Citus_ together with _Slurm_ and _Spark_ (about 400 compute cores in total). So I have many parallel `SELECT` and `INSERT/UPDATE` queries and many concurrent transactions. Most of my tables are relatively small, but some have > 100 million entries. I would like to stick to _PostgreSQL_ for this data instead of using _Cassandra_ or so because I need to perform spatial queries (for which I use _Postgis_). My goal is to horizontally scale-out `INSERT` and `SELECT` statements. It seems that I'm able to achieve this with _Citus_. However, I have to give up `FOREIGN KEY` constraints and thus suffer in terms of data integrity (e.g. I can no longer do `DELETE ON CASCADE`, but need to implement this logic application side).

**Comment by sumedhpathak** [comment]
@HackerMD Thanks for the detailed information. Feel free to reach out for technical help/support at https://www.citusdata.com/about/contact_us. A bunch of us hang out on the Slack channel, and can provide quick technical support.

I'm closing this issue, since its not Documentation related. However, I've referenced the relevant Citus product issues, so feel free to comment on those if you have any questions there.

Thanks!
