### ISSUE TITLE
Add upgrade instructions to upgrade to Citus 6.0 and PostgreSQL 9.6

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#213]
@mtuncer captured our upgrade steps for two upgrade scenarios:

* Upgrade Citus 5.0 to Citus 6.0 -- for PostgreSQL 9.5
* Upgrade PostgreSQL 9.5 to 9.6 -- for Citus 6.0

Once we release Citus 6.0.1, we need to add our upgrade steps to our documentation.

**Comment by sumedhpathak** [comment]
https://docs.google.com/document/d/1J3UDiJ6Nvi8Uk6Og5Uj45U9JZ6pRjqAzjmS_miCSa0Q/edit#heading=h.oqkxbl9nbxqf captures the documentation steps.

**Comment by ozgune** [comment]
@mtuncer -- We're adding these instructions to our docs. Are we happy with the level of testing these instructions received?
