### ISSUE TITLE
Answer frequent questions on multi-tenant data modeling

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#218]
When we talk to users who have multi-tenant applications, we frequently hear the following questions:

* How does this approach handle large tenants? The answer to this question varies depending on OLTP or OLAP workloads.
* Can I isolate a particular tenant?
* How do we handle that varies across tenants?
* What if I have tables that don't naturally fit into tenant_id based sharding?

**Comment by begriffs** [comment]
Now covered in https://docs.citusdata.com/en/v7.3/use_case_guide/multi_tenant.html
