### ISSUE TITLE
Write content to explain the two different replication models for Citus

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus_docs#221]
Refer to [Citus issue](https://github.com/citusdata/citus/issues/998) for more context.

**Comment by begriffs** [comment]
Notes from talking with Sumedh about what this involves.

```
Replication GUC can be coordinator and streaming
  Document that the GUC exists
  Where to document replication itself?
  Give recommendations for the two scenarios:
    MT actually uses foreign keys and also updates
      so the streaming model works better
    Realtime uses a more insert-only approach
  Change https://docs.citusdata.com/en/v6.0/reference/configuration.html#citus-shard-replication-factor-integer
    Also this is not eligible to be changed when repliication GUC is streaming
  Sections dealing with failure handling discuss only one mode of replication (update them)
    https://docs.citusdata.com/en/v6.0/search.html?q=failure+handling&check_keywords=yes&area=default
```

**Comment by begriffs** [comment]
## Why are we implementing it? (sales eng)

### What are the typical use cases?


## Communication goals (e.g. detailed howto vs orientation)

### Good locations for content in docs structure


## How does this work? (devs)

### Example sql

### Corner cases, gotchas

### Are there relevant blog posts or outside documentation about the concept/feature?

### Link to relevant commits and regression tests if applicable

**Comment by begriffs** [comment]
Going with a simpler plan after discussing in person.

**Comment by sumedhpathak** [comment]
@begriffs added 6.1 tag to this issue.
