### ISSUE TITLE
Create Multi-Tenant Reference Architecture

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#222]
We'd like to have a Reference Architecture that explains how to build a multi-tenant database.

For this architecture, we could take our PGConf SV tutorial session and map it to a reference architecture section in our docs: https://www.citusdata.com/blog/2016/11/07/video-and-slides-scaling-your-saas-database/

The following also includes dated ideas around what could go into the reference architecture section:

* Introduction
* Example: Scale your database through co-location. Once we have foreign key constraints and parallel schema changes, add these in.
* Example continued: "Excluded tables" to address the question of other dimensions. With reference tables, we could also swap this. Analytics across tenants
* ORM integration: Primary keys on multiple columns, etc.
* Architectural discussion: Modernize your multi-tenant database
    1. Scalability: How many tenants can your database handle? (Google F1, Salesforce paper, Atlassian)
        * Resource pooling, ease of maintenance (Create Index), performance
    2. Custom fields per tenant: JSONB
    3. Isolation: (a) Function to place tenants into their own shards or (b) PostgreSQL per-row ACL
    4. Modern database: Open-source., PostgreSQL extension, on the cloud (backups, etc.) -- Other?: Cost reduction, ease of maintenance, ruby integration
* Migrating your existing database

**Comment by sumedhpathak** [comment]
Updated this to 7.0

**Comment by sumedhpathak** [comment]
Closing this item as the use-case guide is released.
