### ISSUE TITLE
Document UDF for temporarily removing worker node

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#224]

**Comment by mtuncer** [comment]
## UDF master_disable_node

### Why are we implementing it?
Citus dropped worker configuration file ```pg_worker_list.conf``` from v6.0 onwards. We  have introduced two UDFs ```master_add_node()``` and ```master_remove_node()``` to enable addition and removal of worker nodes.

```master_remove_node()``` requires that worker being removed does not contain any active shard placement. This has prevented s

### What are the typical use cases?

### Communication goals

Reference, mostly. Just some coverage of the fact that VACUUM <dist_table> will actually send that to workers.

### Good locations for content in docs structure

The best place looks like to be the section involving ```master_add_node()``` and ```master_remove_node()```

### How does this work?

### Example sql

```sql
SELECT master_remove_node('node_name', node_port);
```

### Corner cases, gotchas

None worthy of noting.

### Link to relevant commits and regression tests if applicable

### Commit:

### Tests

**Comment by onderkalaci** [comment]
> @mtuncer 
 ### Example sql
```sql
SELECT master_remove_node('node_name', node_port);
```

Shouldn't it be: 
```sql
SELECT master_disable_node('node_name', node_port);
```

**Comment by mtuncer** [comment]
@onderkalaci I was not done. Now it should be ready for review.

**Comment by begriffs** [comment]
Documentation now exists for this UDF so closing this issue. https://docs.citusdata.com/en/v7.3/reference/user_defined_functions.html#master-disable-node

We can investigate the correctness of the documentation in 487 which refers to this issue.
