### ISSUE TITLE
Document how determine the shard to which a dist col value maps

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#225]

**Comment by byucesoy** [comment]
### How does this work?

Citus has a internal logic to map each value to specific shard. Although we do all this mapping behind the scenes, some power users want to know which value maps to which shard (generally for maintanence purposes) With out new UDF `get_shard_id_for_distribution_column` we address this request.

Lots of examples which are self-explaining mostly: https://github.com/citusdata/citus/pull/1048/files#diff-5242c7ad7ecd61a82eec5e268a7717d3

### Corner cases, gotchas
* Hash distributed tables, range distributed tables and reference tables are supported but not append distributed tables.

### Are there relevant blog posts or outside documentation about the concept/feature?

* https://github.com/citusdata/citus/issues/827
* https://github.com/citusdata/citus/issues/879

### Link to relevant commits and regression tests if applicable
* Overall discussion: https://github.com/citusdata/citus/issues/872

* The main PR: https://github.com/citusdata/citus/pull/1048

**Comment by sumedhpathak** [comment]
Came up in customer conversation, so bumping up priority.

**Comment by begriffs** [comment]
@saicitus can you give me more background on why people want to know the exact shard id that distribution column values map to? That will help me put the information in the right place within docs.
