### ISSUE TITLE
Document new create_reference_table API changes

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#229]
We've already document `create_reference_table`, but the implementation is changing significantly in 6.1. Document these changes.

**Comment by begriffs** [comment]
## Why are we implementing it? (sales eng)

### What are the typical use cases?


## Communication goals (e.g. detailed howto vs orientation)

### Good locations for content in docs structure

* Update /reference/user_defined_functions.html#create-reference-table

## How does this work? (devs)

### Example sql

### Corner cases, gotchas

### Are there relevant blog posts or outside documentation about the concept/feature?

* https://github.com/citusdata/citus/issues/827
* https://github.com/citusdata/citus/issues/879

### Link to relevant commits and regression tests if applicable

**Comment by begriffs** [comment]
The referenced Citus core issues are complicated. We'll need to discuss this in person to efficiently fill out the above template.

Also noting that this issue could include the changes proposed in #238.

**Comment by onderkalaci** [comment]
@begriffs I've updated the template with the current status of reference tables. Does that look good? I'll do some minor edits as we integrate the remaining items to Citus core.

Feel free to send a calendar invite or ask questions here to discuss any part.

**Comment by begriffs** [comment]
Thank you! I'll look it over next week after my vacation.
