### ISSUE TITLE
Minor update to tutorial to reflect v6.0 changes

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#240]
In our tutorial section, we create a distributed table and then say the following:

https://docs.citusdata.com/en/v6.0/tutorials/tut-hash-distribution.html

"In addition, these UDF’s create citus.shard_count shards for each table, and save one replica of each shard. " We should update this section to remove the reference to ``citus.shard_count``.

**Comment by samay-sharma** [comment]
@ozgune : Now that we've replaced the tutorial with a new one, are we good to close this?
