### ISSUE TITLE
INSERT INTO SELECT with stable functions works 6.1

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#246]
In #237, we have the following note:

"... Consider what would happen with replication factor greater than one. If you run :code:`now()` on the workers, the two replicas would differ. One surprising way that stable functions can sneak in is using timestamps with timezones (:code:`timestamptz`). Functions dealing with timezones rely implicitly on the timezone configuration parameter and hence are marked stable rather than immutable."

We fixed stable functions for Citus 6.1 and after. We could therefore remove this paragraph once we release 6.1

**Comment by begriffs** [comment]
The warning about stable functions no longer exists.
