### ISSUE TITLE
All 2PCs can be recovered using recover_prepared_transaction

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus_docs#255]
## Why are we implementing it? (sales eng)

When making changes across multiple nodes we do so in a two-phase commit to ensure that either all the nodes commit the changes or none do, to ensure atomicity. 

In a one-phase commit (the current default for `citus.multi_shard_commit_protocol`), a commit message is sent to all the nodes participating in the distributed transaction, but if a failure occurs some nodes might commit while others don't, resulting in data loss. 

In a two-phase commit the commit is preceded by a 'prepare' phase in which the transaction state is durably stored on all the nodes. If this succeeds on all the nodes, it is followed by a commit phase, and otherwise an abort phase. A failure might still occur during the second phase, but since its state is stored the transaction can be committed or aborted at a later time ('recovered'). 

As of Citus 6.0, 2PC recovery a completely manual process which requires the user to figure out whether or not a 2PC succeeded from server logs and connect to the workers and commit or abort individual prepared transactions. As of Citus 6.1, this whole process is performed by running `SELECT recover_prepared_transactions()` on the master node (or in the MX case, every node with metadata). Hopefully in a future version of Citus, this will happen automatically.

### What are the typical use cases?

Reliability of schema changes (DDL), bulk loading (COPY), writes to reference tables, multi-shard update/delete (master_modify_multiple_shards), roll-ups (INSERT..SELECT), MX (metadata syncing).

## Communication goals (e.g. detailed howto vs orientation)

Production users should be aware that,  if they use reference tables and/or have `citus.multi_shard_commit_protocol` set to `'2pc'`, they should routinely (e.g. as a cron job) run `SELECT recover_prepared_transactions()` to make sure that 2PC state gets cleaned and prepared transactions on workers are automatically rolled forward. Pending prepared transactions keep holding on to locks, which could block certain operations. The master also stores records in a local table after every 2PC even if the 2PC was successful, which takes up space.

### Good locations for content in docs structure

Maybe cluster management.

## How does this work? (devs)

When a transaction on the master is about to commit, the master sends `PREPARE TRANSACTION 'citus_0_[unique-id]'` to workers to store the state of remote transactions. In addition, the master inserts a record containing the node ID and  'citus_0_[unique-id]' in the `pg_dist_transaction` table. If one of the remote transaction fails to prepare (e.g. connection was lost, node went down), then the master attempts to abort all the transactions, including the ones that it had already prepared. If the latter fails, it leaves an unaborted prepared transaction on the worker.

If the master commits after the prepare phase, then the `pg_dist_transaction` records become visible, such that the fact that the master meant to commit the remote transaction remains known. After commit, the master attempts to commit all the remote transactions on the workers, but there may again be failures in this process, which leaves an uncommitted prepared transaction.

To appropriately commit or abort prepared transactions that were left dangling as a result of a failure, and to ensure that `pg_dist_transaction` doesn't grow too big, the user can run `SELECT recover_prepared_transactions()`.

The `recover_prepared_transactions` function retrieves all pending prepared transactions from workers that start with `citus_0_`. If there is a corresponding record in `pg_dist_transaction`, then the prepared transaction is committed, otherwise it is aborted. If the commit/abort succeeds, or there was no prepared transaction for the `pg_dist_transaction` record (it was already committed/aborted), then the record is deleted. The function returns the number of transactions that it committed or aborted.

Note that the 0 in citus_0 identifies the node which initiated the 2PC. The master is always 0, workers with metadata (MX) have a unique ID greater than 0.

### Example sql

`SELECT recover_prepared_transactions()`

### Corner cases, gotchas

2PCs will be blocked while `recover_prepared_transactions()` is running.

### Are there relevant blog posts or outside documentation about the concept/feature?

No.

### Link to relevant commits and regression tests if applicable

https://github.com/citusdata/citus/issues/1023
https://github.com/citusdata/citus/blob/master/src/test/regress/sql/multi_transaction_recovery.sql

**Comment by begriffs** [comment]
This is great content, but closing for now. We can incorporate it later.
