### ISSUE TITLE
Document `upgrade_to_reference_table`

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#261]

**Comment by aamederen** [comment]
@metdos @sumedhpathak I am not sure who is the right person to fill this information but I didn't see an issue for this UDF so opened an empty one.

**Comment by metdos** [comment]
Maybe @byucesoy referring to https://github.com/citusdata/citus/issues/970.

**Comment by byucesoy** [comment]
It is already documented here: #229

**Comment by aamederen** [comment]
I am reopening this issue because, although the documentation in #229 includes the parts about `upgrade_to_reference_tables`, they are not merged in the fixing PR #252.

@begriffs @sumedhpathak  do you know why we didn't include the parts about `upgrade_to_reference_table` in #252?

**Comment by sumedhpathak** [comment]
@aamederen Agreed we should document upgrade_to_reference_table. Looks like it was just missed from the original PR. Adding this to the 6.1 milestone.
