### ISSUE TITLE
Scrips in citus-tutorials are not documented

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#262]
In citus-tutorial package, we have 3 scripts and two of them are not used/mentioned in the docs: `start-example-citus-cluster` and `insert-live-wikipedia-edits`. We may use them in a tutorial or update the package to prevent confusion.

**Comment by samay-sharma** [comment]
@ozgune , @aamederen , now that we have a new tutorial, should we close this issue?

**Comment by aamederen** [comment]
@samay-sharma I think so. AFAIS #291 removes the citus-tutorial package altogher.

**Comment by samay-sharma** [comment]
Sounds good. Closing
