### ISSUE TITLE
Use the new API in Citus MX section

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#264]
Currently, in Citus MX section of the docs, we use the old API `master_create_distributed_table` but we should use `create_distributed_table`, alongside some `start_metadata_sync_to_node` calls to workers.

**Comment by begriffs** [comment]
@aamederen can you explain why we also need `start_metadata_sync_to_node` in the example? I'm unfamiliar with that one.

**Comment by aamederen** [comment]
@begriffs so basically when you create an "MX-eligible" table (hash distributed, streaming replicated, RF=1 or reference tables), we previously (5.2 MX times) marked the table as mx table (iscluster) and automatically copy shard metadata to the workers.

With 6.1 MX, we introduced the concept of `metadata workers` which is indicated by the `hasmetadata` column in pg_dist_node. We currently propagate the metadata of MX-eligible tables only to these metadata workers. By default, workers have hasmetadata=false so when we want to use MX, users need to call `start_metadata_sync_to_node` function for each worker, or `SELECT start_metadata_sync_to_node(nodename, nodeport) FROM pg_dist_node;`. When a node is marked for metadata sync, then (1) that node receives the snapshot of the metadata from the coordinator, (2) the node receives all DDL and metadata changes, (3) users can connect to the node and query MX tables from that node.

The motivation for this change is that we basically wanted to separate the node addition and metadata sync step, which may add some overhead, as well as to do some more field testing before actually making it default. Other than that, it can allow us to include "data worker vs. query worker" separation in the future.

**Comment by begriffs** [comment]
On the coordinator node of a Cloud MX demo cluster I get this error:

```sql
SELECT start_metadata_sync_to_node(nodename, nodeport) FROM pg_dist_node;
ERROR:  XX000: operation is not allowed
HINT:  Run the command with a superuser.
LOCATION:  EnsureSuperUser, master_metadata_utility.c:994
```

**Comment by aamederen** [comment]
@begriffs As the error message says, we need superuser for start_metadata_sync_to_node. On the cloud, we automatically run these commands on each worker and don't let users to do harm.

**Comment by sumedhpathak** [comment]
To clarify, @aamederen @marcocitus Do we need to call start/stop metadata-sync calls for Cloud? Or is just replacing `master_create_distributed_table` with `create_distributed_table` sufficient?

**Comment by aamederen** [comment]
@sumedhpathak on cloud you don't need to and cannot call start/stop_metadata_sync_to_node. Therefore, you can just use `create_distributed_table` and use MX!
