### ISSUE TITLE
Use `master_disable_node` in Worker Node Failures section

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#265]
Currently, in `Worker Node Failures` section (under Cluster Management), we mark the placements in the failed node as INVALID before calling `master_remove_node` on the failed node. We should update this part to use `master_disable_node`.

**Comment by begriffs** [comment]
I actually don't see the word `master_remove_node` in https://docs.citusdata.com/en/v7.3/admin_guide/cluster_management.html

Is the current version OK now?

**Comment by begriffs** [comment]
Most code is now colorized by the introduction of the new sphinx theme. Any code that lacks highlighting does so because its language is not specified in a handful of places. Checking syntax highlighting is a checklist item in the open PR for restructuring the main menu, so I'm closing this issue.

**Comment by aamederen** [comment]
Current version looks good to me, thanks!
