### ISSUE TITLE
Create a reference table with data in it in SQL Workarounds page

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#267]
In the workarounds page where we describe creating a reference table for joining a distributed table and a local table, we should describe creating a reference table with the data in it because in the described scenario, the user is joining a distributed table and a local table and this case most likely implies that the local table has some data in it. Therefore, it would be helpful to show a way to convert a local table to a reference table with the data in it.

For that, before calling `create_reference_table` we can rename the local table, create the reference table and COPY the data from the old table to the reference table

**Comment by marcocitus** [comment]
Note that as of 6.2, create_reference_table will automatically load data.

**Comment by onderkalaci** [comment]
We should probably close this @aamederen ?
