### ISSUE TITLE
Mention `master_modify_multiple_shards` in Expiring Data section

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#268]
In Expiring Data section, we only mention `master_apply_delete_command` which works only with append tables. In order to expand this part to hash tables, se can use/mention `master_modify_multiple_shards` instead of/alongside `master_apply_delete_command`.

**Comment by begriffs** [comment]
I don't see `master_apply_delete_command` anymore in https://docs.citusdata.com/en/v7.3/use_case_guide/real_time_dashboards.html#expiring-old-data

Was this the section you were thinking of?

**Comment by aamederen** [comment]
@begriffs I thinks so, but I don't exactly remember now. I think we can close this issue.
