### ISSUE TITLE
Decouple replication of reference tables from master_add_node

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#282]
## Why are we implementing it? (sales eng)

The existing master_add_node function automatically replicates reference tables to the new node. However this is a costly operation. Citus users can now choose to call master_add_inactive_node() instead, and master_activate_node() at a later, more convenient, time.

### Good locations for content in docs structure

https://docs.citusdata.com/en/latest/admin_guide/cluster_management.html#adding-a-worker

### Link to relevant commits and regression tests if applicable

**Comment by begriffs** [comment]
Associated with https://github.com/citusdata/citus/issues/1200

**Comment by sumedhpathak** [comment]
- Note that master_add_node() will also copy reference tables.
- Add master_add_inactive_node() and master_activate_node() in UDF reference section.
- Update metadata in pg_dist_node with new 'active' column.

**Comment by sumedhpathak** [comment]
Looks like #315 is related to this. Since we don't know if that pattern is particularly relevant outside of Cloud, let's close #315, and document as we noted above. If we see that as a common pattern/question, we can revisit documenting how to add/activate nodes.
