### ISSUE TITLE
How to rename columns for distributed tables

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#285]
### Link to relevant commits and regression tests if applicable

**Comment by begriffs** [comment]
Associated with https://github.com/citusdata/citus/issues/633

**Comment by begriffs** [comment]
Given the DDL feature support matrix in #320, what else will we need to cover for this issue?

**Comment by begriffs** [comment]
I believe this issue is redundant given the PR about DDL propagation.

**Comment by sumedhpathak** [comment]
@begriffs Looks like we have an example for column rename. This is currently pushed, but a bit premature given column rename is in 6.2. The other examples are OK. However, this issue can be closed.
