### ISSUE TITLE
Document citus_tools

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#287]
## Why are we implementing it? (sales eng)

Some, but not all, statements propagate to workers. Citus provides utilities to do things on individual workers or shards. People really want to use the lower level functions to run SQL on all worker nodes etc.

### UDFs:
run_command_on_workers
run_command_on_placements
run_command_on_colocated_placements
run_command_on_shards

### What are the typical use cases?

* Create UDFs on workers
```
SELECT run_command_on_workers($cmd$CREATE FUNCTION ..... $cmd$);
```

* Get size of shards (to determine how balanced the cluster is)
```
SELECT * from run_command_on_shards('<table_name>',
$cmd$SELECT pg_size_pretty(pg_total_relation_size('%I'))$cmd$, true)
--The third argument is the **parallel factor**.
--true runs the command across the worker shards in parallel.
--(This argument is optional and it is true by default)
```
* Total relation size:
```
SELECT pg_size_pretty(sum(result::int)) from
run_command_on_shards('<table_name>',
$cmd$SELECT pg_total_relation_size('%I')$cmd$, false);
--false runs the command across the worker shards in a sequential(non-parallel) way.
```
* Total indexes size:
```
SELECT pg_size_pretty(sum(result::int)) from run_command_on_shards('<table_name>',
$cmd$SELECT pg_indexes_size('%I')$cmd$);
```
* Get size of worker databases
```
SELECT * from run_command_on_workers($cmd$SELECT pg_size_pretty(pg_database_size('citus'))$cmd$);
```

* Create triggers on shard
https://gist.github.com/saicitus/74e6de56b77a26d22cc576004d8242b1 (Structure/idea is similar, the trigger creation in the link might not work out of the box because of some syntax issues, could you try fixing them)

### Example sql

```sql
select run_command_on_workers($cmd$ show work_mem; $cmd$);
```

### Corner cases, gotchas

* Can run only queries which return a single column and single row

### Link to relevant commits and regression tests if applicable

**Comment by saicitus** [comment]
Came up in 3 customer engagements.

**Comment by saicitus** [comment]
+1

**Comment by begriffs** [comment]
@saicitus my original notes in this issue from our meeting somehow got erased, so I reconstructed some from memory. In any case please help me fill in the list of utility functions available, the use cases, and sql examples.

**Comment by saicitus** [comment]
@begriffs : For exact usage/arguments you could refer the following links(starting/around the highlighted lines):
1) [Code path](https://github.com/citusdata/citus/blob/54b1ebb14e16b1a700221f3414768bcc1161a79f/src/backend/distributed/citus--6.1-13--6.1-14.sql#L108)
2) [Regress tests](https://github.com/citusdata/citus/blob/54b1ebb14e16b1a700221f3414768bcc1161a79f/src/test/regress/sql/multi_citus_tools.sql#L208)
