### ISSUE TITLE
Section for "Why Citus?"

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#290]
## Why are we implementing it? (sales eng)

The first page in our docs is "What is Citus." We should add a section to answer the more fundamental question of Why.

### Are there relevant blog posts or outside documentation about the concept/feature?

Check out content in https://www.citusdata.com/use-cases

**Comment by begriffs** [comment]
Also: When to Use Citus / Considerations -> Consider linking to www.citusdata.com/use-cases

**Comment by ozgune** [comment]
@begriffs / @sumedhpathak -- Do we have a bit more background on this pull request? I'm just trying to better understand the historical context to it.

Did we want to have a separate section on "Why Citus?"

This issue is related to #791.
