### ISSUE TITLE
Remove inconsistency around how we point users to tutorials

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#293]
We provide single node and multiple node installation steps in our docs. We currently point users to our tutorials after a production multiple node Debian or RHEL install, but don't reference the tutorial from anywhere else.

Our tutorials are designed for single node quick installations. We're also planning to focus on Cloud / Docker in our tutorials' first version.

We should probably (?) remove the reference to tutorials from our production multiple node Debian and RHEL install steps -- unless we had a particular motivation for adding them. We could also add a link to Docker / Cloud steps to point users to our tutorial.

**Comment by sumedhpathak** [comment]
Marking this as prioritized for 7.0. Seems a simple enough change to move the pointer from the multi-node setup to single-node and Cloud/Docker.
