### ISSUE TITLE
Migrate data in create_distributed_table

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus_docs#302]
## Why are we implementing it? (sales eng)

To make migrating existing applications that use PostgreSQL less painful by allowing you to distribute existing tables that contain data.

Currently, migrating an existing application from regular PostgreSQL tables to distributed tables involves copying out the data out of a local table and then copying it back into a distributed table. This has a few substantial drawbacks:

- The user needs to turn off writes in the application
- The user needs to have a machine available with a high bandwidth connection to the Citus coordinator
- Copying data in an out can take a lot of time
- In some cases, the data needs to be temporarily written to a file which requires extra storage space
- In some cases, the distributed tables need to have a different name or schema

In cases where the current PostgreSQL server will act as the Citus coordinator, these problems can now be avoided by calling `create_distributed_table` directly on the existing PostgreSQL table. `create_distributed_table` now copies data from local table to shards. Once. Writes on the table are blocked while the data is migrated and pending writes are handled as distributed queries once `create_distributed_table` commits (or back to local if `create_distributed_table` fails). Reads can continue as normal and will become distributed queries once `create_distributed_table` commits.

We don't immediately delete the local data, which allows users to revert if something goes wrong during migration.

Note: `create_reference_table` also loads data automatically.

### What are the typical use cases?

Scaling out an existing PostgreSQL server without significant downtime by installing Citus, adding worker nodes, and calling `create_distributed_table` on the existing tables.

Two-stage migrations in which the user first migrates from a regular PostgreSQL server to a Citus coordinator node (e.g. on Citus Cloud), and then calls `create_distributed_table` on tables to distribute the tables.

## Communication goals (e.g. detailed howto vs orientation)

The main focus should be on describing migration from regular to distributed tables, this could be part of a larger document which also describes things like pg_dump and Amazon Data MIgration Service.

### Good locations for content in docs structure

The basic functionality can be described in Creating Distributed Tables. There should be a new section on Data Migration.

## How does this work? (devs)

When you call create_distributed_table we effectively do the equivalent of a COPY on a distributed table, but instead of the rows coming from a file, we read them from the local table.

### Example sql

We can now show examples in which we load data prior to running `create_distributed_table`:

```
\COPY github_events FROM 'github_events-2015-01-01-0.csv' WITH (format CSV)

SELECT create_distributed_table('github_events', 'repo_id');
NOTICE:  Copying data from local table...
 create_distributed_table 
--------------------------
 
(1 row)
```

We also have some abilities that we did not have before:

```
CREATE TABLE series AS SELECT i FROM generate_series(1,1000000) i;
SELECT create_distributed_table('series', 'i');
NOTICE:  Copying data from local table...
 create_distributed_table 
--------------------------
 
(1 row)
```

### Corner cases, gotchas

The data is left on disk after `create_distributed_table` and its size will remain visible in `\d+`. 

In case of emergency (e.g. your application turns out to not work properly with distributed tables), this allows you to revert back to the local table. There is no clean way of doing this right now, but you could use the following commands:

```
SELECT master_drop_all_shards('series', 'pubic', 'series');
DELETE FROM pg_dist_partition WHERE logicalrelid = 'series'::regclass;
```

To free up the disk space after distributing data, you need to truncate the local table without truncating the distributed table. For this you can set `citus.enable_ddl_propagation` to off as of https://github.com/citusdata/citus/issues/1265 . It is recommend you do this in a transaction block to avoid accidentally truncating the distributed table (e.g. due to a reconnect, or using pgbouncer in transaction-pooling mode). 

```
BEGIN;
SET LOCAL citus.enable_ddl_propagation TO off;
TRUNCATE series;
-- SELECT * FROM series LIMIT 1; should still returns results
END;
```

When distributing a number of tables with foreign keys between them, it's best to drop the foreign keys before running `create_distributed_table` and recreating them after distributing the tables. They cannot always be enforced when one table is distributed and the other is not.

Foreign- or partitioned tables are not supported.

### Are there relevant blog posts or outside documentation about the concept/feature?

No

### Link to relevant commits and regression tests if applicable

https://github.com/citusdata/citus/pull/1117
https://github.com/citusdata/citus/pull/1265

**Comment by sumedhpathak** [comment]
Thanks for all the detailed info @marcocitus !

@begriffs Added 6.2 milestone to this, since the change has been checked-in.

**Comment by begriffs** [comment]
More ideas for new places in the docs:

* Certainly https://docs.citusdata.com/en/v6.1/dist_tables/ddl.html#creating-and-distributing-tables
  * Might be a subsection about partitioning existing postgresql tables
  * Include the two use-cases
* https://docs.citusdata.com/en/v6.1/reference/user_defined_functions.html#create-distributed-table

**Comment by begriffs** [comment]
@marcocitus by the way this is a gold medal winning 🏅 issue description. Thanks for explaining all that.
