### ISSUE TITLE
Update description for master_modify_multiple_shards

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus_docs#307]
The following [link](https://docs.citusdata.com/en/v6.1/reference/user_defined_functions.html?highlight=master_modify#master-modify-multiple-shards) link states:
```
As the function uses shard metadata to decide whether or not a shard needs to be updated,
it requires the WHERE clause in the query to be on the distribution column. 
```
This above is false.

**This UDF run UPDATES/DELETES on all the shards, it doesn't require WHERE clause on the distribution column. It is basically used for running the above DMLs cross-shard.**

**Example:** Suppose you want to delete older data from your table (which is distributed by say **tenant_id** column)
```
DELETE FROM <table_name> WHERE time_created<'xxxxxxxxx'
```
The above DELETE is cross shard because there is no **=** filter on tenant_id.
You can use master_modify_multiple_shards to run this query:
```
SELECT master_modify_multiple_shards('DELETE FROM <table_name> WHERE time_created<''xxxxxxxxx''');

**Comment by saicitus** [comment]
@begriffs, @sumedhpathak  Could this be prioritized soon? Another customer ran into it.

**Comment by sumedhpathak** [comment]
Marking it for 6.2 release. @begriffs Will move this up in priority on Waffle.
