### ISSUE TITLE
Get partition column of a distributed table

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus_docs#308]
## Why are we implementing it? (sales eng)
Basically if a user wants to get what is the distribution column of a distributed table.

### What are the typical use cases?
Suppose a user forgets the name of the partition column and our error messages indicates say **add filter on partition column**, the user would want to see the partition column of a table.

## Communication goals (e.g. detailed howto vs orientation)
A SQL statement which queries the meta-data table and gets the result.

### Example sql
```
SELECT column_to_column_name(logicalrelid, partkey) 
FROM pg_dist_partition where logicalrelid='<table_name>'::regclass;
```

**Comment by sumedhpathak** [comment]
@begriffs Also adding 6.2 milestone to this. Seems simple enough/straightforward.

**Comment by begriffs** [comment]
This could be an FAQ item or potential in an administration/diagnostics section.
