### ISSUE TITLE
Remove reference to master_create_distributed_table in Citus MX Section

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#324]
We deprecated use of ``master_create_distributed_table`` and ``master_create_worker_shards`` with the Citus 6.0 release.

We currently use these deprecated apis in our [Citus MX section](https://docs.citusdata.com/en/v6.1/cloud/mx.html#scaling-out-a-raw-events-table).

We should revise this section and have it use ``create_distributed_table`` instead. This function will by default create 32 shards. We have flexibility to override this default, but this may not be necessary in this part of our documentation.

**Comment by sumedhpathak** [comment]
We have #264 already open tagged for 6.2. There is also a PR for the issue, so closing this issue in favor of that one.

**Comment by ozgune** [comment]
Awesome!
