### ISSUE TITLE
Reduce the level of nesting in our docs homepage (evaluate)

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#325]
When I visit our docs homepage, most sections have 1-2 levels of nesting.

For example, "About Citus" has at most 3 levels of nesting: What is Citus? -> When to use Citus? -> Real-time Applications and Multi-tenant Applications.

The primary exception to this is our References Section. This section has 4 levels of nesting and includes repetitive information on our main page. In particular, we have the following repetition in our docs homepage:

* User Defined Functions Reference
    * Table and Shard DDL
        * create_distributed_table
            * Arguments
            * Return Value
            * Example
        * create_reference_table
            * Arguments
            * Return Value
            * Example
        * master_create_distributed_table
            * Arguments
            * Return Value
            * Example
... similar for all our public APIs

We probably don't need to repeat **Arguments**, **Return Value**, and **Example** headers for each public APIs in our docs homepage. We may therefore want to reduce the level of nesting in our **Reference** section.

**Comment by begriffs** [comment]
I'll incorporate this feedback into the ongoing menu redesign.

**Comment by begriffs** [comment]
That nesting was fixed, closing.
