### ISSUE TITLE
Document migration via Citus Warp

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#326]
## Why are we implementing it? (sales eng)

Citus Warp is an efficient, reliable way to populate a coordinator node prior to distributing data to workers. Alternatives like copying to/from CSV require more disk space and are less efficient.

### What are the typical use cases?

Migrating from RDS, or other Postgres installations to Citus.

### Are there relevant blog posts or outside documentation about the concept/feature?

There's a private google document with steps and screenshots.

We released a blog post about Citus Warp

**Comment by sumedhpathak** [comment]
https://www.citusdata.com/blog/2017/12/08/citus-warp-pain-free-migrations/

**Comment by begriffs** [comment]
We'll want to condense that blog post, and basically suggest contacting us.

**Comment by begriffs** [comment]
Collected more information on the RDS side, and will work with Lukas later in the week for the warp part.
