### ISSUE TITLE
Docs On Cluster Sizing

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus_docs#331]
[## Why are we implementing it? (sales eng)
Comes up in many sales-eng engagements.

### What are the typical use cases?
**Sharding on tenant -**
For OLTP mostly memory is important, for OLAP - Compute also comes into the picture.
Coming up with a cluster size greater than or equal to the specs of their current db(say single node pg) setup is an option.
Sharding helps in performance even if the cluster size equal to the specs of the current db because:
1) Queries are on smaller tables.
2) Less resource contention.
3) **Adding tenant_id to tables/queries makes the queries optimized.**
 
**Sharding on entity -**
Mantra:Performance is directly proportional to the compute-number of cores (considering working set is in memory)

### Link to relevant commits and regression tests if applicable
](url)

**Comment by sumedhpathak** [comment]
@begriffs This looks like a dupe. Could you check if this content is now captured in our sizing section?

**Comment by begriffs** [comment]
Covered in https://docs.citusdata.com/en/v7.2/admin_guide/production_sizing.html
