### ISSUE TITLE
No citus 6.1 version available in ubuntu 16.04

### ISSUE THREAD

**Issue by Raptory** [citusdata/citus_docs#333]
Hi I tried to install on my machine with Ubuntu 16.04 citus the way it is in your docs

`curl https://install.citusdata.com/community/deb.sh | sudo bash &&
sudo apt-get -y install postgresql-9.6-citus-6.1`

But there is only package postgresql-9.6-citus, which installs version 6.0.
Is it something wrong with the script deb.sh? Can I install it some other way?

**Comment by sumedhpathak** [comment]
Hi there. I am not able to reproduce the issue. Running the similar commands on Ubuntu 16.04 VM on EC2 installs Citus 6.1 just fine. Is there an error or any message you get when running either in the repo install or the package?

**Comment by Raptory** [comment]
Yes, when I try to run 
`sudo apt-get -y install postgresql-9.6-citus-6.1`
I get 
E: Unable to locate package postgresql-9.6-citus-6.1
E: Couldn't find any package by glob 'postgresql-9.6-citus-6.1'
E: Couldn't find any package by regex 'postgresql-9.6-citus-6.1'

There is only package postgresql-9.6-citus available.

But what's more important, there is an error when trying to install repo (which is probably the cause of the problem):
Installing /etc/apt/sources.list.d/citusdata_community.list... bash: line 186: curl: command not found
Unable to run: 
    curl https://repos.citusdata.com/community/config_file.list?os=Ubuntu&dist=xenial&source=script

This is weird, because curl is installed on my machine.

**Comment by Raptory** [comment]
Well, I had some unmet dependencies, running apt-get -f install fixed it and after that I could install repo successfully.
