### ISSUE TITLE
Document node size upgrade and, node scale-out

### ISSUE THREAD

**Issue by craigkerstiens** [citusdata/citus_docs#337]
Citus Cloud provides self-service scaling up and out of nodes. Each of these has slightly different behavior, but do accomplish a similar upgrade process. 

## Communication goals

Orientation and how-to as well

### Good locations for content in docs structure

This likely lives it it's own section under cloud around upgrades. In the future we may want to add content about citus version and postgres upgrades as well. 

## How does this work? (devs)

In the case of an instance upgrade. We bring stand-by's of the new instance type online. Once those instances are fully caught up in transactions to the primary for each node we remove the IP from the primary, attach it to the stand-by, bring the stand-by out of recovery so it is now acting as the primary. We do this for each node as it's caught up. The impact is seconds for each node, though an overall cluster size increase could be minutes depending on when each is ready.

If you have a maintenance window set we run this operation during that time frame. If no maintenance window is set we run it as soon as the stand-bys are ready.

For scaling out. We bring new nodes online and set them up with Citus. You'll see within the Citus dashboard that new nodes are being added to the cluster. Once all new nodes are added you then need to run the rebalancer to introduce them to the cluster and have data redistributed to them. *Add more context on rebalancing and co-location*

### Are there relevant blog posts or outside documentation about the concept/feature?

https://www.citusdata.com/blog/2017/03/23/a-look-into-disaster-recovery-and-high-availability-and-how-they-work-with-postgres-on-citus-cloud/

**Comment by begriffs** [comment]
More notes:

* How to increase node size and also node number
  * Include screenshots, can grab some from Craig’s blog post
  * When does the node size change happen
    * As soon as ready (if no maintenance window), create a standby ~ 40 min. Per 100 GB of data
    * HA failover
  * Scaling out
    * Boot new nodes, you monitor in dashboard, should be 5-10 minutes
    * Run rebalancer
      * You have to run the rebalancer yourself, it won’t happen automatically on resize. It’s manual because it takes locks that prevent inserts
      * Document to run only 1 table and all co-located tables are rebalanced

**Comment by begriffs** [comment]
@lfittl what are the reasons to choose upgrading instances over adding new nodes and vice versa? Also, is there any more info about how upgrades work that I should be aware of?

**Comment by lfittl** [comment]
@begriffs Re: upgrades vs more nodes, I'm trying to think of a good generic answer to this. Maybe @craigkerstiens has one?

Re: how upgrades work: We bring up a follower (same mechanism as we use for HA) with the new instance type, and then do a really quick failover once its caught up. That failover will occur in your configured maintenance window (which you can choose in the Settings tab).

**Comment by craigkerstiens** [comment]
There's not a huge reason to pick one vs. the other. One factor is the amount of data you have sitting in disk. If you're closer to filling up disk then you'll want to add more nodes and rebalance. If you still have a lot of headroom on disk but see performance suffering by scaling up nodes you can improve that. Though for most cases either operation can be fine and give you the performance improvement you're looking for.
