### ISSUE TITLE
Clarify (lack of) ORC—cstore compatibility

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/citus_docs#338]
[`cstore_fdw`'s `README`](https://github.com/citusdata/cstore_fdw/blame/a602765a0b2fdb87d228081a9cb045e160678fb7/README.md#L16-L18) says—without qualification—_This extension uses the Optimized Row Columnar (ORC) format for its data layout_; however, what's actually used is an adapted ORC format (involving PostgreSQL serialization and compression functions, skip indexes, etc.).

That one sentence can mislead. Several blog posts (e.g. [here](https://blog.dbi-services.com/optimized-row-columnar-orc-format-in-postgresql/) and [here](http://tech.marksblogg.com/billion-nyc-taxi-rides-postgresql.html)) imply `cstore_fdw` is a way to add ORC support to PostgreSQL, though one could hardly blame them as [one of our own webinars](https://www.citusdata.com/blog/2015/09/01/cstorefdw_webinar/) says _ We will take a deeper dive into the Optimized Row Columnar (ORC) storage format that cstore_fdw uses_.

I discovered the above after a Drift conversation predicated on the assumption that we could just read ORC files. To avoid such confusion in the future, we should clarify our documentation.

**Comment by begriffs** [comment]
@jasonmp85 which section of docs were you thinking should cover this? The topic seems kind of obscure.

**Comment by begriffs** [comment]
I'm just reviewing issues to see which are still pressing. @jasonmp85 any thoughts about my previous question?
