### ISSUE TITLE
We don't have "Transitioning From PostgreSQL to Citus" page for 6.1

### ISSUE THREAD

**Issue by metdos** [citusdata/citus_docs#342]
We have the same link for 5.2
https://docs.citusdata.com/en/v5.2/admin_guide/transitioning_from_postgresql_to_citus.html

However, the link on the page above fails for 6.1
https://docs.citusdata.com/en/v6.1/admin_guide/transitioning_from_postgresql_to_citus.html

Search for "Transitioning From PostgreSQL to Citus" can not find anything.
https://docs.citusdata.com/en/latest/search.html?q=Transitioning+From+PostgreSQL+to+Citus&check_keywords=yes&area=default#

**Comment by begriffs** [comment]
We now have this "Transitioning to Citus" section: https://docs.citusdata.com/en/v7.3/migration/transitioning.html

Closing this issue, but reopen if it's not what you had in mind.
