### ISSUE TITLE
Document the Cloud status RSS feeds

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#343]
## Why are we implementing it? (sales eng)

To monitor events in the life of a formation from outside tools via a standard format, we offer RSS feeds per organization.

### What are the typical use cases?

@lfittl do we have anecdotes of customers using this feature? Do they connect the feed up to a notification system or something?

## Communication goals (e.g. detailed howto vs orientation)

Our goal is to make people aware of this feature.

### Good locations for content in docs structure

Perhaps as a subsection of Cloud → Logging.

## How does this work? (devs)

Point a feed reader at the url provied by the "Formation Events" link in the upper right of the formations page. The feed will include events for

* Failover Scheduled, includes:
  * Formation name
  * Formation url
  * Leader
  * Failover at
* Failover
  * Formation name
  * Formation url
  * Leader
  * Situation
  * Follower
* Server Unavailable
  * Formation name
  * Formation url
  * Server

**Comment by lfittl** [comment]
@begriffs Various use cases - one thing to mention might be integration into Slack (i.e. you could have database activity show up in an `#ops` channel)
