### ISSUE TITLE
How to connect to the Cloud database

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#344]
## Communication goals (e.g. detailed howto vs orientation)

Teach people the connection options for optimal security and speed.

### Good locations for content in docs structure

A new subsection of Cloud about getting started, probably after a section about creating formations.

## How does this work? (devs)

To connect to a Cloud formation, users must use a PostgreSQL connection string. We'll begin by explaining the anatomy of the string, such as where the username, password, host, db etc are written. Show where to find the string in the Cloud console. Note too that we require SSL.

Users have the option to connect directly via port 5432 or through pgBouncer on 6432. The regular port imposes a hard limit of 300 connections to limit memory consumption, but pgBouncer allows any number of connections while effectively throttling the number of active connections into the db itself. @lfittl are there any pgBouncer limits I should know about, or other gotchas?

### Corner cases, gotchas

Some shells (zsh?) require escaping query params on the connection string such as `\?ssl_required=`.

### Are there relevant blog posts or outside documentation about the concept/feature?

**Comment by lfittl** [comment]
@begriffs Its important to mention the number of active connections you have - as thats going to be a limiting factor even when using pgbouncer.

You can measure this on a system using `SELECT COUNT(*) FROM pg_stat_activity <> 'idle'`. Note that for Postgres 10 (not released yet) that query will likely have to look like this: `SELECT COUNT(*) FROM pg_stat_activity <> 'idle' AND backend_type = 'client backend'` to correctly exclude background processes.

There is also a limit on pgbouncer itself for inbound connections (idle and active counted together) which is currently set to 2000 connections - but subject to change, and typically you'd be limited by active connections first.

**Comment by lfittl** [comment]
@begriffs One additional thing I remembered:

We've been meaning to document how to use `sslmode=verify-full` to connect to a Citus Cloud database. Could we add this here as well?

Essentially one needs to download our certificate from https://console.citusdata.com/citus.ca into a location on your local machine/application server, and then reference it using `?sslrootcert=/location/to/citus.crt&sslmode=verify-full` in the connection string.
