### ISSUE TITLE
We don't explicitly explain automatic failover in Cloud features

### ISSUE THREAD

**Issue by metdos** [citusdata/citus_docs#347]
https://docs.citusdata.com/en/v6.1/cloud/features.html

This question is asked on Drift channel;
https://app.drift.com/inboxes/25613/conversations/13485444?statusFilter%5B%5D=OPEN

Related to #330

**Comment by begriffs** [comment]
We now have an Availability/Recovery section in Cloud: https://docs.citusdata.com/en/v7.3/cloud/availability.html

Closing this issue, but reopen if that section is not what you had in mind.
