### ISSUE TITLE
How to enable db security on the workers?

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#350]
## Why are we implementing it? (sales eng)

For convenience, our multi-node setup docs instruct people to use "trust" authentication in `pg_hba.conf` in for local network addresses. However many users have asked how to enable stronger security.

### What are the typical use cases?

In a multi-tenant use case using row-level security to keep information strictly hidden between clients, stronger permissions are required to ensure that clients can connect to workers as only their own role.
(@lfittl this is only my guess, is it accurate?)

### Good locations for content in docs structure

A new "Security" subsection under Cloud

## How does this work? (devs)

It is possible to require passwords on the workers. If you put worker nodes' password  into a .pgpass file on the master, the master will use the password to connect. Some queries (some joins we call repartition joins) also require that the workers connect to each other, for those queries to work you'll have to put the .pgpass file onto the workers as well.

### Are there relevant blog posts or outside documentation about the concept/feature?

https://www.postgresql.org/docs/current/static/libpq-pgpass.html

**Comment by lfittl** [comment]
@begriffs I think row-level security is a separate topic, and it'd require some more testing before we can document and recommend it as a general use case.

For security here I'd simply focus on the PostgreSQL roles, and the fact that this allows you to create read-only users, or users that are only allowed to query and/or write to certain tables.

**Comment by begriffs** [comment]
I originally imagined this as a "Security" section in our Cloud docs, but it seems applicable beyond Cloud. Maybe it should go in a new "Administration -> Security" section instead.
