### ISSUE TITLE
Document why UNIQUE indexes on non-partition columns are unsupported

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#363]
Relevant support thread:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/citus-users/O3eDLxcsEfw/141NJea7BAAJ

## Why are we implementing it? (sales eng)
People see an error but don't know why.

## Communication goals (e.g. detailed howto vs orientation)
Document why its not supported. What are the technical reasons why it would not work well.

### Good locations for content in docs structure
DDL/FAQ or both?

**Comment by begriffs** [comment]
The google group link doesn't behave quite right, but the relevant part of the discussion is:

> I think the offending problem here is the UNIQUE index on URL:
CREATE UNIQUE INDEX "url_url" ON "url" ( "url" );
>
> As a distributed system, for Citus can gaurantee uniqueness only if the unique index is on the partition column. That is because the shards are split so that each shard contains non-overlapping partition column values. The index on the worker node can then enforce the constraint.
>
> In this example, if we were to enforce a unique index on URL, Citus would need to check every shard on every INSERT to validate uniqueness, which defeat the scalability goals. You could either distribute your table on URL (if you expect that to be unique, or include rec_id column in the unique index.
