### ISSUE TITLE
Document citus.multi_task_query_log_level

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#372]
## How does this work? (devs)

Allows one to error or warn on queries which run in parallel (for multi-tenant use-cases). Probably worth documenting as part of a migration step. (e.g. set to ERROR during testing to see if all queries have been migrated to suitable multi-tenant ones).

### Link to relevant commits and regression tests if applicable
https://github.com/citusdata/citus/pull/1316

**Comment by lfittl** [comment]
For this it'd be worth documenting both the logging use case (just have cross-shard queries show up - potentially something one could use in production) as well as the enforcement use case (actually error out for cross-shard queries - this one would likely only use in their test suite)
