### ISSUE TITLE
Django integration

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#375]
## Why are we implementing it? (sales eng)

Many people have expressed interest in Citus for use as the backend for multi-tenant Django apps.

## Communication goals (e.g. detailed howto vs orientation)

Either documentation for @saicitus' python library, or if that is not ready then a cleaned-up version of his Django workaround notes. The goal is a howto that allows users to modify their Django apps.

**Comment by samay-sharma** [comment]
We had a meeting today to discuss how to go about this. There are 2 pieces of content we need to draft:-

(a) Schema migration
(b) App / Query migration.

For (a), @saicitus would share a document on this issue which lists the changes we need to make based on customer experiences. @begriffs can then take that and turn it into a PR.

For (b), the idea is to document the library. Before we get started on that, @saicitus would write some tests for it and we'll do some internal testing. Based on the feedback from that, we can start drafting content for it.

**Comment by saicitus** [comment]
@begriffs I have shared the schema-migration document with you. I have reviewed it recently and did some changes. You could take a look at it, proof-read and make suitable changes before publishing it in our docs.
