### ISSUE TITLE
Partitioning by hash+time

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#377]
### What are the typical use cases?

A timeseries database on Citus.

### Good locations for content in docs structure

Mention timeseries data in the realtime section of
https://docs.citusdata.com/en/v7.2/sharding/data_modeling.html

Probably add a detailed section showing how to use pg_partman and link to it from that overview.

### Are there relevant blog posts or outside documentation about the concept/feature?

https://www.citusdata.com/blog/2018/01/24/citus-and-pg-partman-creating-a-scalable-time-series-database-on-PostgreSQL/

### Link to relevant commits and regression tests if applicable

https://github.com/citusdata/citus/issues/183

**Comment by sumedhpathak** [comment]
@ozgune Just to clarify, we will be deprioritizing this for Docs.

**Comment by begriffs** [comment]
Reprioritized in docs meeting today.
