### ISSUE TITLE
add examples how to use FOREIGN TABLE for shard

### ISSUE THREAD

**Issue by KES777** [citusdata/citus_docs#39]
In the [DOC](https://www.citusdata.com/docs/citus/5.0/reference/metadata_tables.html#shard-storage-types) you mention that 'f' flag for storage type is used to 
`Indicate that shard stores foreign data. (Used by distributed file_fdw tables)` 
But there is not any examples how to use that. Also it is unclean is it possible to use mysql_fdw tables for shards?
If so how to create and configure such shards?

**Comment by begriffs** [comment]
Actually looks like this very cursory coverage is still the case in the v7 docs - https://docs.citusdata.com/en/v7.0/reference/metadata_tables.html#shard-storage-types

It seems to me that the only place that talks about how to use this is one of our blog posts. https://www.citusdata.com/blog/2016/06/10/scaling-mysql-with-citus/

Not sure whether this use case is really our focus though, so I'm tentatively closing this issue.

**Comment by KES777** [comment]
Any features are useless if people will not know how to use it. So you should document each carefully.
And documentation priority should not be less than feature development which documentation describes.

If you not sure you should not close.
