### ISSUE TITLE
Enable different scrolling for sidebar vs main content

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#395]
This has bugged me for a while, but I am unable to independently scroll the LHS index, and expand sections without losing my place due to the whole page loading.

**Comment by begriffs** [comment]
This is fixed in the menu redesign branch. I'll close this issue when that one is merged.

**Comment by begriffs** [comment]
Many sections can now scroll independently of the menu, but not Table Management, Multi-Tenant Tutorial and probably others.

**Comment by begriffs** [comment]
We're doing what we should in our project configuration. This appears to be a RTD theme bug and I filed https://github.com/rtfd/sphinx_rtd_theme/issues/629

/cc @samay-sharma

**Comment by begriffs** [comment]
The menu and content now scroll independently.
