### ISSUE TITLE
Improvements to MT use case guide

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus_docs#399]
I'm merging the use case guide into master (https://github.com/citusdata/citus_docs/pull/365), but I wanted to track some minor feedback. @begriffs : We can look to fix it as a follow-up PR early next week.

1) We say "For SaaS applications, each tenant’s data can be isolated and kept invisible from other tenants. This is efficient in three ways. First application improvements apply to all clients. Second, sharing a database between tenants uses hardware efficiently. Last, it is much simpler to manage a single database for all tenants than a different database server for each tenant."

The benefits are of running a single instance of database to store all tenants data.

Can we make it. "For SaaS applications, each tenant’s data can be isolated and kept invisible from other tenants. However, running a single database instance to handle all your tenants is efficient in three ways. ....."

2) In preparing tables and ingesting data:
"Citus requires that primary and foreign key constraints include the distribution column. This requirement makes enforcing these constraints much more efficient in a distributed environment as only a single node has to be checked to guarantee them."

3) Highlight all COPY commands in the Try it yourself section.

4) In when data differs across tenants: "The database administrator can even create a partial index to improve speed for an individual tenant’s query patterns. Here is one to improve company 5’s filters for browser information:"

The query creates an index on the ismobile dimension and not on browser info. Can we fix the text there?

5) Now that we have the scaling on Citus Cloud section, could we update the "Scaling Hardware Resources" section to become shorter?

**Comment by samay-sharma** [comment]
To scale out your Citus cluster, you can first add a new worker node to the Citus cluster. To do this on Citus Cloud, you can use the slider present in the "Settings" tab to add the required number of nodes. If you have your own Citus installation, you can do this by using the master_add_node UDF.

One you add the node, the new node will be available in the system, but at this point no tenants are stored on it so Citus will not yet run any queries there. To move your existing data, you can ask Citus to rebalance the data.
This operation moves bundles of rows called shards between the currently active nodes to attempt to equalize the amount of data on each node. Rebalancing preserves Table Co-Location, which means we can tell Citus to rebalance the companies table and it will take the hint and rebalance the other tables which are distributed by company_id.

Applications do not need to undergo downtime during shard rebalancing. Read requests continue seamlessly, and writes are locked only when they affect shards which are currently in flight.

**Comment by samay-sharma** [comment]
Other than ^, all the other sections look good. So, feel free to incorporate the above and then merge :).

**Comment by begriffs** [comment]
Cool, will do.
