### ISSUE TITLE
Document support for different clusters

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#420]
## Why are we implementing it? (sales eng)
We are adding support for "followers", or read-only clusters.

We are adding a few different GUC's:
Add the `citus.read_from_secondaries` and `citus.current_cluster` GUCs
Add the `nodecluster` column, including as parameters to `master_add{,_inactive}_node`

See: https://github.com/citusdata/citus/pull/1518/files. 

This is still WIP, so contents of the PR might change. Primarily there are some metadata changes and possibly UDF changes/additions we might want to document.

**Comment by begriffs** [comment]
Info about read_from_secondaries in https://github.com/citusdata/citus/pull/1540

**Comment by lithp** [comment]
Dropping a note that we also added [`master_add_secondary_node`](https://github.com/citusdata/citus/pull/1542), which makes using this feature a little nicer.
