### ISSUE TITLE
Minor Documentation Mistakes

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus_docs#423]
When I read our documentation, I think there are some points which need quick fixes. 
1. On our [FAQ](https://docs.citusdata.com/en/v6.2/faq/faq.html) page we have two questions as 
* [How do I change the shard count for a hash partitioned table?](https://docs.citusdata.com/en/v6.2/faq/faq.html#how-do-i-change-the-shard-count-for-a-hash-partitioned-table)
* [How do I choose the shard count when I hash-partition my data?](https://docs.citusdata.com/en/v6.2/faq/faq.html#how-do-i-choose-the-shard-count-when-i-hash-partition-my-data)
and the answer is the same for both questions;
> Optimal shard count is related to the total number of cores on the workers. Citus partitions an incoming query into its fragment queries which run on individual worker shards. Hence the degree of parallelism for each query is governed by the number of shards the query hits. To ensure maximum parallelism, you should create enough shards on each node such that there is at least one shard per CPU core.
We typically recommend creating a high number of initial shards, e.g. 2x or 4x the number of current CPU cores. This allows for future scaling if you add more workers and CPU cores.

This is a right answer to the question _"How do I choose the shard count when I hash-partition my data?"_. However, this is not answering the question _"How do I change the shard count for a hash partitioned table?"_

2. In the [page](https://docs.citusdata.com/en/v6.2/sharding/colocation.html#colocation), where Table Co-Location feature is presented, we have a figure explaining the hash distribution on shards and the ranges are wrong. As it can be seen in the following picture 
![figure](https://docs.citusdata.com/en/v6.2/_images/colocation-shards.png)
For NODE2, shard number 4 and 8, the hash range must be 1073741824<= x <= 2147483647.

3. When I read the [definition](https://docs.citusdata.com/en/v6.2/reference/user_defined_functions.html#create-distributed-table)  of create_distributed_table from our documentation, this part

> If the table is hash-distributed, the function also creates worker shards based on the shard count and shard replication factor configuration values. If the table contains any rows, they are automatically distributed to worker nodes.

I thought that I can also use the method to re-distribute a table according to the new shard count and shard replication factor configuration variables. However, it is not supported (yet)

**Comment by furkansahin** [comment]
Hey @begriffs,
I put the above issues all together under one issue but should I open separate issues?

**Comment by begriffs** [comment]
Hey thanks for pointing these out. I do usually like to have a separate issue for each thing just for tracking purposes. Want to close this one and split it up?

**Comment by furkansahin** [comment]
Sure!
