### ISSUE TITLE
FAQ - Incorrect answer

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus_docs#426]
On our [FAQ](https://docs.citusdata.com/en/v6.2/faq/faq.html) page we have two questions as 
* [How do I change the shard count for a hash partitioned table?](https://docs.citusdata.com/en/v6.2/faq/faq.html#how-do-i-change-the-shard-count-for-a-hash-partitioned-table)
* [How do I choose the shard count when I hash-partition my data?](https://docs.citusdata.com/en/v6.2/faq/faq.html#how-do-i-choose-the-shard-count-when-i-hash-partition-my-data)
and the answer is the same for both questions;
> Optimal shard count is related to the total number of cores on the workers. Citus partitions an incoming query into its fragment queries which run on individual worker shards. Hence the degree of parallelism for each query is governed by the number of shards the query hits. To ensure maximum parallelism, you should create enough shards on each node such that there is at least one shard per CPU core.
We typically recommend creating a high number of initial shards, e.g. 2x or 4x the number of current CPU cores. This allows for future scaling if you add more workers and CPU cores.

This is a right answer to the question _"How do I choose the shard count when I hash-partition my data?"_. However, this is not answering the question _"How do I change the shard count for a hash partitioned table?"_

**Comment by sumedhpathak** [comment]
@furkansahin Do you have a suggestion here? Thanks!

**Comment by begriffs** [comment]
We're tracking this as part of #454, so closing this one.
