### ISSUE TITLE
Co-location page figure error

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus_docs#427]
In the [page](https://docs.citusdata.com/en/v6.2/sharding/colocation.html#colocation), where Table Co-Location feature is presented, we have a figure explaining the hash distribution on shards and the ranges are wrong. As it can be seen in the following picture 
![figure](https://docs.citusdata.com/en/v6.2/_images/colocation-shards.png)
For NODE2, shard number 4 and 8, the hash range must be 1073741824<= x <= 2147483647.

**Comment by furkansahin** [comment]
This issue persists

**Comment by begriffs** [comment]
Yep, I see it's still wrong in the 7.3 docs.
