### ISSUE TITLE
Single machine installation guide query fix

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus_docs#437]
In this [page](https://docs.citusdata.com/en/latest/installation/single_machine_deb.html), the queries that we provide to add worker nodes to the coordinator is 
```
psql -p 9700 -c "SELECT * from master_add_node('localhost', 9701);"
```
```
psql -p 9700 -c "SELECT * from master_add_node('localhost', 9702);"
```
This is not wrong but incomplete because psql just tries to connect to the database with the name of the current user when we do not put it into the command. So, I think that we should write the queries so that it uses the default postgres database.
```
psql postgres -p 9700 -c "SELECT * from master_add_node('localhost', 9701);"
```
```
psql postgres -p 9700 -c "SELECT * from master_add_node('localhost', 9702);"
```

When we install postgres from a package manager it generally creates the user postgres as well. However, this is not the case when we go with a source code build.

**Comment by sumedhpathak** [comment]
@furkansahin We also have this statement in the instructions:
`sudo su - postgres`

Isn't this sufficient? Our goal for these instructions was meant to follow from the instructions from the start. If one follows those instructions, all the commands work right? Thanks.

**Comment by furkansahin** [comment]
@sumedhpathak You are right. It is sufficient if one is following the initial steps we provide.
For me, the case was different. I built from the source code and followed the instructions to setup a cluster. Thus, I just omitted the first a couple of instructions and I run into that issue.
Now, I understand the goal of these instructions better and see that my case is out of the focus. 

Shall we include another section describing the installation from source code?

**Comment by begriffs** [comment]
First: just identify which sections I would change, and how hard it would be. A general scoping and time estimate.

**Comment by begriffs** [comment]
@furkansahin the building from source instructions are currently in https://github.com/citusdata/citus/blob/master/CONTRIBUTING.md but we could move that into the documentation.

**Comment by begriffs** [comment]
Actually, talking with Sumedh, we thought the build instructions are more for developers than users, so we're inclined to leave that out of docs.
