### ISSUE TITLE
Workarounds refers to table without providing its definition

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus_docs#441]
In our [SQL Workarounds](https://docs.citusdata.com/en/latest/reference/sql_workarounds.html#sql-workarounds) page we provide a couple of queries which are all supposed to run on a table called events. However, we do not provide the definition of that table. Of course in the previous pages of the documentation the query is available as following;
```
CREATE TABLE events(event_id bigint, 
                    event_type text, 
                    event_public boolean,
                    repo_id bigint,
                    payload jsonb,
                    repo jsonb,
                    user_id bigint,
                    org jsonb,
                    created_at timestamp);
```
But I thought it would be better to add this query to the somewhere on top of this page so that if a user came directly to that page from google, etc. it will be easier to follow the documentation for him.

**Comment by begriffs** [comment]
This section has gotten a lot simpler and now refers to a `github_events` table. We simply say:

> Suppose we have a table called github_events, distributed by the column user_id. Then the following window function will not work:

Think we should still copy the definition of this table into this page? Or is it good enough to note the distribution column and leave it up to the reader's imagination?

**Comment by furkansahin** [comment]
I think it is good enough to leave it like this.
