### ISSUE TITLE
Append reference query fix

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus_docs#442]
In the [reference page for append distribution](https://docs.citusdata.com/en/latest/reference/append.html), there is this query introducing ```master_append_table_to_shard```.
```
SELECT * from master_append_table_to_shard(102089, 'github_events_temp', 'master-101', 5432);
```
However, when we follow the instructions, we can see that we did not yet created a table called ```github_events_temp```. So, it might be better to run the query with a table that we are sure that it exists. For example;
```
SELECT * from master_append_table_to_shard(102089, 'github_events', 'master-101', 5432);
```

**Comment by sumedhpathak** [comment]
This isn't quite right, as the intent is to first load data into a *local* table on the master (or any postgres instance). 

See this comment:
```
To use the above functionality, you can first insert incoming data into a regular PostgreSQL table. You can then create an empty shard using master_create_empty_shard(). ```

So the pattern is to:
1. Create github_events_temp (temp is probably the wrong word here, 'local' might be better).
2. Load data into it via Inserts/copy
3. Append data from this table into shard 102089.
The shard creation can happen only once.

The change you are suggesting would load from the *distributed* github_events table into a single shard. 

Closing this, as the contents are correct.
