### ISSUE TITLE
Sizing a citus cluster

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus_docs#453]
## Why are we implementing it? (sales eng)
To help users/prospects/customers come up with the right cluster size.

### What are the typical use cases?
Multi-tenant use cases.
Real-time use cases

### Good locations for content in docs structure
May be a small section which talks about it.

## How does this work? (devs)
**Multitenant SAAS usecases (sharding on tenant)id)**
What we generally recommend to customers/prospects is to choose a cluster such that the hardware(total number of cores and total RAM) on workers is same as that of existing postgres (or other single node db) instance. In such scenarios we have seen 2-3x performance improvements because of sharding and improvement resource utilization.
In case of coordinator size, choose a compute optimized box because coordinator is mostly used for routing queries to the right workers. Depending on the existing workload(write/read throughput) you can go with suitable number of cores.
In Citus cloud by default workers are of the type r4s and coordinator is c4s.

**Realtime Analytics usecases (shard on entity_id)**
**Total Cores:** Considering working data in memory(RAM), ideally you can expect linear performance improvement with the number of cores. Suppose you are on single node db (ex postgres). Based on i) what performance you are getting with the current database and ii) what is the expected requirement with citus, you can decide what is the number of cores. For ex you are currently getting on avg 10s latency on postgres and are looking at 1s latencies, you might choose total 10 cores on workers. 
**RAM:**
In terms of RAM on workers, ideal/best case would be go with RAM such that the majority of the working set fits memory. Working set depends on the queries (filters on the say time)

**Comment by sumedhpathak** [comment]
@begriffs This can be closed I presume?
