### ISSUE TITLE
Update the real-time use case guide

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#469]
The guide https://docs.citusdata.com/en/v7.0/use_case_guide/real_time_dashboards.html is way outdated. Using the latest Citus features will make it a lot simpler.

**Comment by furkansahin** [comment]
During the testing, I run this code from real-time use case guide
```SQL
SELECT
  site_id, minute,
  jsonb_object_agg(request_country, country_count)
FROM (
  SELECT
    site_id, date_trunc('minute', ingest_time) AS minute,
    request_country,
    count(1) AS country_count
  FROM http_request
  GROUP BY site_id, minute, request_country
) AS subquery
GROUP BY site_id, minute;
```

and it doesn't run since Citus does not support jsonb_object_agg, just fyi

**Comment by begriffs** [comment]
Thanks for the report, yeah I'm about to fix that whole section.
