### ISSUE TITLE
Window functions on distribution col now supported

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#475]
Update https://docs.citusdata.com/en/v7.0/reference/sql_workarounds.html#data-warehousing-queries and anywhere else they are mentioned

**Comment by begriffs** [comment]
Actually I'm moving this back to the "Next Up" column after looking into it. I'd like to actually see this feature working so I can definitively update the section with "this works, but this doesn't." Ultimately it's an a section trying to show how to use a temp table to work around lack of sql support. So I'll still want an example of the window function failing, but failing on a non-distribution column.

**Comment by begriffs** [comment]
I tried this feature again from Citus built off master (at 9a04b789). Verified that the extension reports itself as `7.1-3` in my local db. Using the schema and data from the [RT analytics tutorial](https://docs.citusdata.com/en/v7.0/tutorials/real-time-analytics-tutorial.html) I tried a window function.

```sql
SELECT
    repo_id,
    count(*) OVER (PARTITION BY user_id)
FROM
    github_events;
```

I thought it would work according to https://github.com/citusdata/citus/pull/1668 because `user_id` is the distribution column of `github_events`. Instead it says:

```
ERROR:  0A000: could not run distributed query with window functions
HINT:  Consider using an equality filter on the distributed table's partition column.
LOCATION:  ErrorIfQueryNotSupported, multi_logical_planner.c:1856
```

@furkansahin did I make a mistake in my query or misunderstand the feature in your pull request?

**Comment by furkansahin** [comment]
The PR I opened implements the window function support for only SUBQUERY PUSHDOWN and INSERT INTO SELECT. Thus, your query should be 
```
SELECT 
    * 
FROM
    (SELECT
         repo_id,
         count(*) OVER (PARTITION BY user_id)
     FROM
         github_events
    ) foo;
```
When I try this query in Citus master branch, it gives me the results.
