### ISSUE TITLE
Support for count(distinct) on non-dist column

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#476]
It used to be possible only by using an approximation:

```
ERROR:  cannot compute aggregate (distinct)
DETAIL:  table partitioning is unsuitable for aggregate (distinct)
HINT:  You can load the hll extension from contrib packages and enable distinct approximations.
STATEMENT:  select count(distinct what) from todos;
ERROR:  0A000: cannot compute aggregate (distinct)
DETAIL:  table partitioning is unsuitable for aggregate (distinct)
HINT:  You can load the hll extension from contrib packages and enable distinct approximations.
LOCATION:  ErrorIfUnsupportedAggregateDistinct, multi_logical_optimizer.c:2604
```

Update https://docs.citusdata.com/en/v7.0/dist_tables/querying.html#count-distinct-aggregates and other places in docs that cover it. Show the new possibilities.

**Comment by begriffs** [comment]
@mtuncer are there any caveats I should note? Like does a count distinct on non-distribution column need to pull lots of rows into the coordinator?

**Comment by mtuncer** [comment]
There is possible performance issue when there are many distinct column. The way it works is
```sql
select count(distinct a) from table_a
```

gets translated to following worker and coordinator queries.
```sql
select a from table_a_XXX group by a;
select count(distinct a) from worker_query_result;
```

In other words, workers perform distinct operations and send rows to coordinator, then coordinator performs count(distinct) operation on them. Normally this should be fine however, one could write a following query

```sql
select count(distinct a), count(distinct b), count(distinct c) from table_abc;
```
Which translates to
```sql
select a, b, c from table_abc_xxx;
select count(distinct a), count(distinct b), count(distinct c) from worker_query_result
```

Depending on the cardinality of each column, we may end up returning a lot of rows from worker query. This has 3 possible performance implications:
1. costly group by at each worker
2. transfer of large number of rows from each worker to coordinator node
3. handling of a large data at coordinator

If a user suffers from those problems we should advise them to use approximate count distinct using hll.

**Comment by mtuncer** [comment]
I run some numbers on performance
I had a table t1(a int, b int, c int) with 15M rows with each item has about 1M distinct values. Table is hash partitioned among a with 4 shards to 4 workers.

select count(distinct a) from t1 --> took ~8 seconds in which all time is spent on workers
select count(distinct b) from t1 --> took ~23 seconds   (worker : 17, coordinator: 6)
select count(distinct a), count(distinct b), count(distinct c) --> 105 secs (w: 41 c:  64)
select a, count(distinct b) from t1  group by a --> took ~22 seconds  (w: 17.5, c: 4.5)
select b, count(distinct c) from t1  group by b --> took ~83 seconds  (w: 35, c: 48)

Then I enabled hll by setting error rate to 0.01;
select count(distinct a) from t1 --> dropped to 2.8 secs from 8  (almost all on worker)
select count(distinct b) from t1 --> dropped to 2.8 secs from 8  (almost all on worker)
select count(distinct a), count(distinct b), count(distinct c) --> 5 secs (almost all on worker)
select a, count(distinct b) from t1  group by a --> took ~376 seconds  (w: 28, c: 348)
select b, count(distinct c) from a1 group by b --> took ~415 seconds  (w: 40, c: 375)

Note: coordinator time also contains time spend during data transfers, and serialize/deserialize operations.

I should mention that these tests are performed on a memory restricted device, therefore the last 2 hll tests might not be representative as it caused postgres to use more memory than available and caused memory swapping to disk.

**Comment by metdos** [comment]
> select a, b, c from table_abc_xxx;

@mtuncer, here can we add group by a,b,c?

**Comment by mtuncer** [comment]
@metdos edited
