### ISSUE TITLE
Make it clear that shard rebalancing happens "online"

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#477]
## Communication goals (e.g. detailed howto vs orientation)

We want people to know the capability of our rebalancer, to brag a little bit. Otherwise they might mistakenly believe it entails significant downtime.

### Good locations for content in docs structure

Add detail about shard rebalancing under [cluster management](https://docs.citusdata.com/en/v7.0/admin_guide/cluster_management.html).

## How does this work? (devs)

Read queries continue without interruption. Write queries are queued on the coordinator until the shards they reference are in their new places.

### Are there relevant blog posts or outside documentation about the concept/feature?

* https://www.citusdata.com/blog/2017/04/11/rebalancing-your-database-with-citus/

**Comment by onderkalaci** [comment]
This is the internal [documentation](https://docs.google.com/document/d/1SEQ6ruRf_8-8Lx_QMNAZrH2N_FJelgv8QKpEYb7DbwM/edit#) that briefly explains how shard rebalancer has changed with 7.1. Feel free to set a meeting to discuss it further.

The pull requests that enabled us this:

1. https://github.com/citusdata/citus-enterprise/pull/194
2. https://github.com/citusdata/citus-enterprise/pull/196
3. https://github.com/citusdata/citus/pull/1743

The PRs that makes it easy to set replica identity of the distributed tables:
1. https://github.com/citusdata/citus/pull/1731
2. https://github.com/citusdata/citus/pull/1734
3. https://github.com/citusdata/citus/pull/1739

Team meeting slides: https://docs.google.com/presentation/d/1nx_vwT7hoXVEqfBBKATC7-WUaZvwtIAq8J2b0jOcu2c/edit#slide=id.g2749ef4f17_0_32
