### ISSUE TITLE
Rebundle tutorial and test for 5.1

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#49]
Check `INSERT` especially

**Comment by sumedhpathak** [comment]
As per @onderkalaci there is no issue with the INSERT's and the new tutorial. However, we should re-bundle tutorials with 5.1. I'm updating the title to reflect that.

**Comment by sumedhpathak** [comment]
The OS X tutorial uses Postgres 9.5.0, but the Linux one uses 9.5.1. When we rebundle, let's make sure both bundles use the same Postgres version.

**Comment by begriffs** [comment]
Ran into what seems to be a blocker for rebuilding the citus-tutorial package. https://github.com/citusdata/citus/issues/384

@lithp have you encountered this and do you know a workaround?

**Comment by begriffs** [comment]
I also discovered the problem is fixed in Citus v5.1.0-rc.1 but I don't want to bundle a release candidate in the tutorial package.

**Comment by sumedhpathak** [comment]
@begriffs This should now be fixed in master and 5.1 release branch. Could you verify?
