### ISSUE TITLE
Elaborate on the use of pgBouncer on Cloud

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#491]
## Why are we implementing it? (sales eng)

(Consult the sources listed below and fill this in)

## Communication goals (e.g. detailed howto vs orientation)

Explain how and why an app connects to the cluster through pgBouncer, and also how/why nodes connect to one another this way as well.

### Good locations for content in docs structure

The section https://docs.citusdata.com/en/v7.0/cloud/security.html talks about connecting to Cloud through pgBouncer, but this content isn't very visible. We'll want a new Cloud (sub)section for it. Craig suggests under a main "Scaling" topic.

### Are there relevant blog posts or outside documentation about the concept/feature?

There should be details about pgBouncer in one of the recorded team presentation, and in the dev@ list.

**Comment by begriffs** [comment]
We now have a "Cloud > Scaling > Scaling Connections (pgBouncer)" section. This motivates that connections consume resources and how to use Cloud's built-in pgbouncer.

**Comment by sumedhpathak** [comment]
I don't remember the motivation here, but was it more to describe the pgBouncer architecture?
