### ISSUE TITLE
Update FAQ answer to indicate that we support cross node transactions

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus_docs#499]
https://docs.citusdata.com/en/v7.0/faq/faq.html#are-there-any-postgresql-features-not-supported-by-citus

The answer says that we do not support "Transactional semantics for queries that span across multiple shards". We do support that for DDLs, COPYs and for single row inserts now which span multiple shards. We're also expanding support to cross shard updates and deletes. We should update this answer to indicate that.

**Comment by begriffs** [comment]
@samay-sharma this looks like it matches the item "Document that transactions work" we talked about in the SE meeting. I see you tagged it as "outdated," how come?
