### ISSUE TITLE
Searched for MX. Clicked on the search result and hit "Sorry, this page doesn't exist"

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#513]
I went to our documentation, and typed "mx" in the search window.

Two results showed up: MX (Beta) and Scaling Out Data Ingestion.

I clicked on MX (Beta), and it took me to this URL: https://docs.citusdata.com/en/v7.0/cloud/mx.html?highlight=mx

In this page, I received the "Sorry, this page does not exist" response.

**Comment by begriffs** [comment]
This happened to me for another Cloud page as well. I moved some of the pages to new sections and it looks like their full text search database is stale. Found a similar problem reported on the Read The Docs repo itself. Going to add a report of our problem there.

**Comment by begriffs** [comment]
Doing a search for MX on 7.3 lists links that all work.
