### ISSUE TITLE
Better definition of %I vs %s in interpolated queries

### ISSUE THREAD

**Issue by jasoncox** [citusdata/citus_docs#527]
Docs reference %I and then show an example using %s.

From: https://github.com/citusdata/citus_docs/blob/master/extra/query_propagation.rst

Notice the %I which will be replaced with each shard's name.

```
-- Get the estimated row count for a distributed table by summing the
-- estimated counts of rows for each shard.
SELECT sum(result::bigint) AS estimated_count
FROM run_command_on_shards(
  'my_distributed_table',
  $cmd$
    SELECT reltuples
      FROM pg_class c
      JOIN pg_catalog.pg_namespace n on n.oid=c.relnamespace
     WHERE n.nspname||'.'||relname = '%s';
  $cmd$
);
```

**Comment by begriffs** [comment]
This is fixed now in http://docs.citusdata.com/en/v8.1/develop/reference_propagation.html#running-on-all-shards

Thanks for reporting.
