### ISSUE TITLE
github link has wrong link

### ISSUE THREAD

**Issue by chaintng** [citusdata/citus_docs#539]
Right now, it link to this : https://github.com/citusdata/citus_docs/blob/origin/v7.0/aboutcitus/introduction_to_citus.rst (ERROR 404)
Which suppose to be this:
https://github.com/citusdata/citus_docs/blob/v7.0/aboutcitus/introduction_to_citus.rst

We should omit the `origin` in the path.

![image](https://user-images.githubusercontent.com/2979072/32826635-bebdd5fc-ca1b-11e7-94e5-01d7e2132ac6.png)

**Comment by chaintng** [comment]
It is here https://github.com/citusdata/citus_docs/blob/v7.0/_themes/citus/breadcrumbs.html#L19
Why sphinx display `github_version` for `origin/v7.0` ?

**Comment by begriffs** [comment]
Looks like our new theme leaves out that incorrect "origin" part of the path. Thanks for reporting!
