### ISSUE TITLE
Add instructions to preserve pg_dist_node_metadata during upgrades

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/citus_docs#542]
We have instructions to copy our metadata table rows into `public` tables before a `pg_upgrade` and then to copy them back after.

Citus 7.1 adds a new table, `pg_dist_node_metadata`, which stores a server identifier and other information used by our usage collection feature. We want the server identifier to remain constant across upgrades (to track adoption), so dumping and restoring it is necessary as well.

**Comment by jasonmp85** [comment]
Just noticed this isn't closed; did it get updated?

**Comment by begriffs** [comment]
No, it still isn't mentioned in https://docs.citusdata.com/en/v7.3/admin_guide/upgrading_citus.html

**Comment by begriffs** [comment]
Confirmed that dist_node_metadata is now in the instructions. It was added in d1815402
