### ISSUE TITLE
INSERT SELECT via coordinator doesn’t support upserts

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#560]
## Communication goals (e.g. detailed howto vs orientation)

Warn people it won't work. `ON CONFLICT` fails when you run the query on the coordinator. Scan for any places we might contradict that. Also check whether plain `INSERT .. ON CONFLICT` is good, because we mention that too.

### Good locations for content in docs structure

* Might be time to add INSERT SELECT to the DML section as a subsection. It is mentioned in passing other places but is a significant form of DML. Include the on conflict warning as a highlighted note.
* The workarounds section if there's a workaround (perhaps filtering by a single tenant).

**Comment by sumedhpathak** [comment]
`ERROR:  cannot plan queries which include both local and distributed relations`
`ERROR:  ON CONFLICT is not supported in INSERT ... SELECT via coordinator`

Seen this a couple of times with customers, so upping its priority.

**Comment by marcocitus** [comment]
Workaround for `INSERT INTO dest_table <query> ON CONFLICT <upsert clause>`:
```sql
BEGIN;
CREATE UNLOGGED TABLE temp_table (LIKE dest_table);
SELECT create_distributed_table('temp_table', 'tenant_id');
INSERT INTO temp_table <query>;
INSERT INTO dest_table SELECT * FROM temp_table <upsert clause>;
DROP TABLE temp_table;
END;
```

If we implement it, Citus will likely do something similar under the hood.

**Comment by sumedhpathak** [comment]
@marcocitus I presume this is still an issue right?
