### ISSUE TITLE
Document workaround for Insert into local-table, select from distributed table.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#562]
`insert into foo(colA, colB) select A,B from bar` where `bar` is distributed and `foo` is not,

**Comment by begriffs** [comment]
And the reverse direction is #80

**Comment by begriffs** [comment]
Verified this is still a restriction in v8.1. The error message itself gives a workaround suggestion though.

```
ERROR:  cannot INSERT rows from a distributed query into a local table
HINT:  Consider using CREATE TEMPORARY TABLE tmp AS SELECT ... and inserting from the temporary table.
```

**Comment by begriffs** [comment]
The error message is good enough that I'm closing this issue.
