### ISSUE TITLE
Document new recursive query planner

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#571]
## Why are we implementing it? (sales eng)

Citus is adding a new query planning mode for Improved SQL support of subqueries and CTEs.

## Communication goals (e.g. detailed howto vs orientation)

Recursive execution allows new queries, but sometimes isn't a good choice for performance. When the subquery returns too much information, the network overhead to send it to the coordinator can be too high. We want to help people determine if this is the case, and if so modify the query to be router executable if possible. Include examples of a slow recursive executor query and its modification.

### Docs changes needed

* Adjust workarounds section
  * Remove https://docs.citusdata.com/en/v7.1/reference/sql_workarounds.html#subqueries-in-where
  * Just wrap local table in subquery/CTE https://docs.citusdata.com/en/v7.1/reference/sql_workarounds.html#join-a-local-and-a-distributed-table
  * https://docs.citusdata.com/en/v7.1/reference/sql_workarounds.html#window-functions
    * No change for this one. Still requires the workaround.
  * Test and remove section https://docs.citusdata.com/en/v7.1/reference/sql_workarounds.html#data-warehousing-queries
    * The Citus on my system which identifies itself as `7.2-3` is still unable to partition a window function on a non-distribution column. Tried moving that part into a subquery but got the same error, so leaving this section unchanged.
  * Add sections for features where router query workaround exists with perf implications. **Question**: I can see how filtering a query for router execution will make it work, but why are there "perf implications?" Seems like it would run quickly, albeit limiting information to a single tenant.
    * Aggregate distinct other than count(distinct), for instance sum(distinct) and avg(distinct)
    * array_agg with ORDER BY
    * window functions on non-partition keys
* Expand claims in SQL coverage section https://docs.citusdata.com/en/v7.1/reference/citus_sql_reference.html
  * Reverse the section: it's much shorter now to list the things we *don't* support than those we *do*.
    * Correlated subqueries (that are not pushdownable)
    * Recursive/modifying CTEs
    * Table sample
    * SELECT … FOR UPDATE
    * Grouping sets
    * There are a few exceptional combinations of CTEs and subqueries that do not yet work. However they eventually will. Do we document them now or just wait?
* Query Processing https://docs.citusdata.com/en/v7.1/performance/query_processing.html
  * Add the router executor
  * Show how executors can be mixed with recursive planning and their intermediate results brought together as short-lived reference tables
  * Give an outline of how Citus decides which execution strategy to use
    * Like, "first it tries to push down, and if it can't then … Finally the logic applies recursively to CTEs and subqueries"
* https://docs.citusdata.com/en/v7.1/performance/performance_tuning.html
  * Talk about discovering and fixing bottlenecks that are due to inadvertent use of recursive planning
  * Where the recursive planner *is* required, talk about limiting/filtering in ctes/subqueries when possible
    * `WITH cte_slow AS (SELECT * FROM users_table) SELECT * FROM cte_slow LIMIT 10;`
    * vs `WITH cte_fast AS (SELECT * FROM users_table LIMIT 10) SELECT * FROM cte_fast;`
  * The `citus.max_intermediate_result_size` GUC can help cancel accidental `SELECT * FROM big_table` subqueries
  * Beware of queries whose top-level is router executable but has large intermediate results -- this will force computation on a single core. Give an example.
* FAQ
  * Handling errors due to `max_intermediate_result_size` violation
  * Things are looking better in "Are there any PostgreSQL features not supported by Citus?"
* GUC reference
  * Add max_intermediate_result_size
* Other pull requests which are slightly invalidated (update them before merging)
  * #553 - the "naive" query will actually work
  * #544 - the suggestion to make per-tenant views is no longer necessary
  * #563 - touches an area of the FAQ that will have to be changed

### Link to relevant commits and regression tests if applicable

https://github.com/citusdata/citus/issues/1804
(The main issue about it, with PRs linking to it)

**Comment by sumedhpathak** [comment]
The team meeting presentation also had good content about this.
