### ISSUE TITLE
Fix canonical links (again)

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#590]
Read The Docs still overrides our canonical link, despite the work in https://github.com/citusdata/citus_docs/pull/581.

I created an RTD issue about it - https://github.com/rtfd/readthedocs.org/issues/3474 - but aside from a thumbs-up nobody has replied yet.

We can try extending the "extrahead" block of the RTD template as suggested by https://github.com/rtfd/readthedocs.org/issues/815 and implemented by https://github.com/Wacc1314/python-packaging-user-guide/blob/42c52e40932675adbbc2114a20dafb989dad0649/source/themes/pydoctheme/_templates/page.html

**Comment by begriffs** [comment]
I nudged the RTD thread, not sure when they will fix this.

**Comment by jonels-msft** [comment]
The canonical links are now in place. They don't really help our SEO issue about old vs new versions, but they are in place.
