### ISSUE TITLE
2pc is a default option, documentation bug

### ISSUE THREAD

**Issue by Splarv** [citusdata/citus_docs#603]
Bug in the documentation.
https://docs.citusdata.com/en/v7.2/dist_tables/ddl.html

> By default Citus performs DDL with a one-phase commit protocol. For greater safety you can enable two-phase commits by setting

SET citus.multi_shard_commit_protocol = '2pc';

But as I can see.

=> show citus.multi_shard_commit_protocol;
 citus.multi_shard_commit_protocol 
-----------------------------------
 2pc
(1 row)

2pc is a default protocol.

**Comment by begriffs** [comment]
@Splarv thanks for the report -- the new version of Citus defaults to 2pc as you pointed out. I pushed a change to the docs to reflect that.
