### ISSUE TITLE
master_move_shard_placement is not documented

### ISSUE THREAD

**Issue by Splarv** [citusdata/citus_docs#604]
master_move_shard_placement is not documented in the section Citus Utility Function Reference.
https://docs.citusdata.com/en/v7.2/reference/user_defined_functions.html

**Comment by sumedhpathak** [comment]
@Splarv this UDF is in our Enterprise package only. Are you looking to use this function for a specific use-case? Thanks.

**Comment by Splarv** [comment]
@sumedhpathak , just readed docs. I see this is fixed in documentation of 7.3
