### ISSUE TITLE
Subquery improvements in 7.3

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#611]
## Why are we implementing it? (sales eng)

We're trying to get full SQL coverage for the real-time use case. With recursive planning and `pull&push` execution, we've enabled a bunch of subqueries. The improvements here are also implemented using the same infrastructure and aims to fill the missing types of SQL (sub)queries.

### What are the typical use cases?

The actual goal is to enable full SQL coverage for real-time use-case and as described below we'll mostly use it for that use case. However, the boundaries between `real-time` and `data warehouse` are not very straight. So, some of the query types we've enabled could be used in `data warehouse` use case as well. Though, we probably wouldn't want to document that. I just wanted to mention it here for a broader explanation.

## How does this work? (devs)

With [#1804](https://github.com/citusdata/citus/issues/1804) (and related PRs), Citus gained the ability to plan subqueries that are not pushdownable as it is.

There are two high-level requirements for pushing down subqueries such that none of the inner subqueries could have any of the following:

- Individual subqueries that require a merge step (i.e., GROUP BY on non-distribution key, or LIMIT in the subquery etc). We've handled such subqueries via [#1876](https://github.com/citusdata/citus/issues/1876).
 - Combination of subqueries that are not joined on distribution keys. This change enables to recursively plan some of the subqueries that are not joined on distribution key to make the whole query safe to pushdown.

The very basic idea is that we pick an `anchor` subquery among all the subqueries in the given query. Later, we compare the remaining subqueries with our `anchor` subquery. If both are not colocated (e.g., not joined on the distribution key), we recursively plan the other subqueries.

### Example sql

This change enabled quite a lot of different types of subqueries. I'd like to bucket the examples into 3 categories for ease of discussion:

### 1.Subqueries in `WHERE` clause
With this change, we've enabled all types of subqueries in `WHERE` clause. Previously, we'd expected two things for running subqueries in `WHERE` clause 

-  The subquery contains a distribution key equality with the `FROM` clause subqueries such as [[1]](https://github.com/citusdata/citus/blob/master/src/test/regress/sql/multi_subquery_in_where_clause.sql#L9) or [[2]](https://github.com/citusdata/citus/blob/master/src/test/regress/sql/multi_subquery_behavioral_analytics.sql#L464) 
-  The subquery requires a merge step (e.g., `GROUP BY` on non distribution key or `LIMIT`) so that it is recursively planned such as [[3]](https://github.com/citusdata/citus/blob/master/src/test/regress/sql/subquery_basics.sql#L184). 

This change alleviates the first bullet listed above (note that the second bullet is already covered in the previous releases). 

Now that whenever we see a subquery in `WHERE` clause which is not `colocated` (i.e., do not contain distribution key equality), we recursively plan that subquery. An example:

```SQL
-- the join is via `NOT IN` expression, which is used to be never safe to pushdown
-- so recursively plan subquery in WHERE clause
    SELECT
        count(*)
    FROM
        events_table
    WHERE
        user_id
    NOT IN
        (SELECT user_id FROM events_table WHERE event_type = 2);
```
Or such as:
```SQL
-- the join is via `IN` expression, which is not safe to pushdown since it is not on distribution key
-- so recursively plan subquery in WHERE clause
    SELECT
        count(*)
    FROM
        events_table
    WHERE
        event_type
    IN
        (SELECT event_type FROM events_table WHERE value_2 IN (1,2,3,4));
```

So, we ended up with supporting all kinds of subqueries in `WHERE` clause.

### 2.Subqueries in `FROM` clause that are not joined on distribution column

Previously, we'd expected each subquery to be joined on the distribution key. Now that we'd recursively plan some of the `non-colocated` subqueries (e.g., not joined on the distribution key) and make the whole query run in Citus:

```SQL
-- foo is individually safe to pushdown and joined on distribution keys
-- bar is individually safe to pushdown and joined on distribution keys
-- However, join among foo and bar is not on the distribution keys, so not safe to pushdown 
-- since the join is on `value_2`

    SELECT
        foo.value_2
    FROM
        (SELECT 
        	users_table.value_2 
        FROM 
        	users_table, events_table 
        WHERE 
        	users_table.user_id = events_table.user_id AND event_type IN (1,2,3,4)) as foo,
        (SELECT 
        	users_table.value_2 
        FROM 
        	users_table, events_table 
        WHERE 
        	users_table.user_id = events_table.user_id AND event_type IN (5,6,7,8)) as bar
    WHERE
        foo.value_2 = bar.value_2;
-- recursively plan bar such that the query becomes safe to pushdown
DEBUG:  generating subplan 5_1 for subquery SELECT users_table.value_2 FROM public.users_table, public.events_table WHERE ((users_table.user_id = events_table.user_id) AND (events_table.event_type = ANY (ARRAY[5, 6, 7, 8])))
```

### 3.Individual subqueries that are not colocated (i.e., repartition joins in subqueries):

This is similar to the above item. However, this time I'd mention about the case where any of the subqueries is a re-partition join among distributed tables.

An example:
```SQL
-- note that foo contains a join which requires repartitioning (e.g., `users_table.user_id = events_table.value_2 `)
SELECT count(*)
FROM
  (SELECT 
    users_table.user_id
   FROM 
    users_table, events_table
   WHERE 
    users_table.user_id = events_table.value_2 AND event_type IN (1,2,3,4)) AS foo,
  (SELECT users_table.user_id
   FROM users_table, events_table
   WHERE users_table.user_id = events_table.user_id AND event_type IN (5,6,7,8)) AS bar
WHERE foo.user_id = bar.user_id

-- foo is a repartition join, thus recursively plan in
DEBUG:  generating subplan 19_1 for subquery SELECT users_table.user_id FROM public.users_table, public.events_table WHERE ((users_table.user_id = events_table.value_2) AND (events_table.event_type = ANY (ARRAY[1, 2, 3, 4])))
```

### Any combination of the above 3 items

Though I've mentioned each item separately, we're able to support any combination of such cases. For example, a subquery in WHERE clause could contain a repartition join [[1]](https://github.com/citusdata/citus/pull/2016/files#diff-66b4d5132326cad97436bc2f153b26ceR49)  or you could have subqueries that involve all of the above properties such as [[2]](https://github.com/citusdata/citus/pull/2016/files#diff-66b4d5132326cad97436bc2f153b26ceR80)

### Corner cases, gotchas

* Citus is able to recursively plan subqueries. In some cases, bare relations (e.g., relations that are not inside a subquery) may be non-colocated with the anchor subquery. We fail to support those queries. An example is below:
```SQL
-- note that u1 and u2 are not inside a subquery, they are just part of a regular join among two tables
-- the result of the join of u1 and u2, which is identified with `join_res` is joined with another subquery

-- So in the following query Citus fails to pick an anchor subquery (or relation) 
-- such that it could recursively plan the remaining and the query becomes OK
 
   SELECT 
        count(*) 
    FROM
        (users_table u1 JOIN users_table u2 using(value_1)) join_res JOIN (SELECT value_1, random() FROM users_table) as u3 USING (value_1); 
```

 The workaround is to simply wrap the join `join_res` into a subquery or CTE.

* Citus may create non-optimal plans if the query contains any set operations. In certain cases with set operations, Citus may aggressively recursively plan more queries than what is actually needed. I don't think that is very important. Just wanted to note for future reference.

### Link to relevant commits and regression tests if applicable

https://github.com/citusdata/citus/pull/2016

**Comment by begriffs** [comment]
Thanks for the great notes, @onderkalaci !

@sumedhpathak I'm not sure that there's anything I need to change in docs because of this. We never get detailed enough about subquery limitations for there to be claims to remove from the docs.

The main sections about it are [push pull](https://docs.citusdata.com/en/v7.2/performance/query_processing.html#subquery-cte-push-pull-execution) and [subquery network overhead](https://docs.citusdata.com/en/v7.2/performance/performance_tuning.html#subquery-cte-network-overhead) and they look OK. I also grepped for `subquer(y|ies)` to scan for other mentions but they're minor.

I could add a section to describe the remaining gotchas, but most things are supported so not sure it's worth it.

**Comment by sumedhpathak** [comment]
@onderkalaci Great notes! Do we capture these in a Doc somewhere? If not, could we copy these into a Google Doc and put it in the Dev folder?

@begriffs Agreed that not much needs to change. We do have that workaround for the unsupported query, so that might be something we document at some point. I don't think its critical to document right now, and we can wait to see if customers encounter the issue.

**Comment by onderkalaci** [comment]
> If not, could we copy these into a Google Doc and put it in the Dev folder?

I added to Dev (team) -> Documentation (team): [here](https://drive.google.com/drive/u/0/folders/0B8k-_HsMY1TtWVN2eVlTcENnZFE)
