### ISSUE TITLE
Documentation for run_command_on_shards() doesn't match example

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#617]
@taybin opened up an issue in the Citus repository: https://github.com/citusdata/citus/issues/2014 I'm copy/pasting the issue below.

https://docs.citusdata.com/en/v7.2/extra/query_propagation.html#running-on-all-shards

The documentation says:
> Notice the %I which will be replaced with each shard’s name.

but the example code uses `%s`

This also makes the documentation for `run_command_on_colocated_placements()` confusing because it uses both `%s` and `%I` and doesn't explain which is for which table.

**Comment by ozgune** [comment]
@begriffs -- How long would it take to fix this issue?

**Comment by begriffs** [comment]
@ozgune -- looks quick, I can take care of it next. I'll test it out and open a pull request.
