### ISSUE TITLE
Remove google analytics key in config file

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#623]
Our `conf.py` file for Sphinx specifies:

```ini
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
  'analytics_id': 'UA-xxxxxxxx-x'
}
```

The sphinx_rtd_theme documentation [claims](https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html#base-options) that this parameter enables google analytics tracking. However https://github.com/rtfd/sphinx_rtd_theme/issues/477 indicates that this parameter has been broken on and off since 2014. It may be fixed in the future by pull request https://github.com/rtfd/sphinx_rtd_theme/pull/411 

I propose that we remove the `analytics_id` in `html_theme_options`. Let's continue to rely on the analytics code included by RTD hosting itself. This latter code is configurable via the admin panel for our project, and on each deployment RTD injects  into `/_static/readthedocs-dynamic-include.js`.

<details>
<summary>More details about the RTD injected tracking code</summary>
When un-minified, this is precisely what their code tracks with google:
<pre><code>
(function(i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function() {
        (i[r].q = i[r].q || []).push(arguments)
    }
    ,
    i[r].l = 1 * new Date();
    a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
}
)(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
ga('create', 'UA-17997319-1', 'auto', 'rtfd');
ga('rtfd.set', 'dimension1', READTHEDOCS_DATA.project);
ga('rtfd.set', 'dimension2', READTHEDOCS_DATA.version);
ga('rtfd.set', 'dimension3', READTHEDOCS_DATA.language);
ga('rtfd.set', 'dimension4', READTHEDOCS_DATA.theme);
ga('rtfd.set', 'dimension5', READTHEDOCS_DATA.programming_language);
ga('rtfd.set', 'dimension6', READTHEDOCS_DATA.builder);
ga('rtfd.send', 'pageview');
ga('create', 'UA-xxxxxxxx-x', 'auto', 'user');
ga('user.send', 'pageview');
</code>
</pre>
This shows that they track our page views on both their own analytics account and on the "user" one we specify.
</details>
<br/>

/cc @sumedhpathak @clairegiordano

**Comment by jonels-msft** [comment]
I don't think the setting in conf.py is even having an effect, so no reason to mess with it. There is a comment near it explaining.
