### ISSUE TITLE
Explanation of master_disable_node is not clear

### ISSUE THREAD

**Issue by velioglu** [citusdata/citus_docs#628]
As an explanation of `master_disable_node`, it is stated that the UDF is removing the node from the cluster temporarily. However, DML commands continue to affect tables on inactive nodes, which is expected as a functionality. We may elaborate the explanation.

**Comment by sumedhpathak** [comment]
Hey Burak, we have an existing issue, where we've had more detailed conversation. :)
See #487.  Unfortunately the implementation itself is a bit mixed, so elaboration requires some verbal gymnastics. 

Closing this issue in favor of that one.
