### ISSUE TITLE
All links fail without Google Analytics

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#63]
This technique aborts link clicks with the `return false` when a browser privacy extension blocks access to GA. This may not affect very many people, but wanted to point it out.

```html
<a
  href="https://packages.citusdata.com/tutorials/citus-tutorial-osx-1.1.0.tar.gz" 
  onclick="trackOutboundLink('https://packages.citusdata.com/tutorials/citus-tutorial-osx-1.1.0.tar.gz'); return false;"
>Download</a>
```

/cc @craigkerstiens

**Comment by jasonmp85** [comment]
Just hit this myself (and updated the title). On the multi-machine page the Citus Cloud link fails as well as the CloudFormation link. I have Ghostery installed and it blocked Google Analytics from loading.
