### ISSUE TITLE
Enable local connections to trust in pg_hba.conf - Repartitioning queries failure

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus_docs#66]
Tested Version: v5.1.0-rc.1
Created two tables and tried to execute a repartition join.

The query failed with the following error on master
```
ERROR:  failed to execute job 11
DETAIL:  Too many task tracker failures
```
In the worker log this was the error:
```
2016-05-18 00:48:03 UTC [8246-1] postgres@postgres LOG:  could not receive data from client: Connection reset by peer
2016-05-18 00:48:03 UTC [4127-419] WARNING:  could not connect to node localhost:5432
2016-05-18 00:48:03 UTC [4127-420] DETAIL:  Client error: fe_sendauth: no password supplied
```

This was resolved after I changed pg_hba.conf on the worker
```
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                     trust
```

**Steps to Reproduce**

```SQL
CREATE TABLE large1(id bigint, val bigint);
CREATE TABLE large2(id bigint);
```
citus.large_table_shard_count was by default 4.
Made both the above tables large tables with different partition columns.

Hash distributed the large1 table with val as the partition column.
```SQL
select master_create_distributed_table('large1','val','hash');
select master_create_worker_shards('large1',16,1);
```

Hash distributed the large2 table with id as the partition column.
```SQL
select master_create_distributed_table('large2','id','hash');
select master_create_worker_shards('large2',16,1);
```

Did a few inserts:
```SQL
INSERT INTO large1(id,val) VALUES(1,1)
INSERT INTO large1(id,val) VALUES(1,2)
INSERT INTO large2(id) VALUES(1);
```
Ran the join query which requires repartitioning
```SQL
set citus.task_executor_type to 'task-tracker';
SELECT COUNT(*) FROM large1,large2 where large1.id=large2.id;
```

**Comment by samay-sharma** [comment]
@sumedhpathak @begriffs , Should we add this to the 5.1 release milestone?

Our docs don't explicitly demonstrate repartitioning scenarios, but since our docs are the recommended way of getting Citus setup, we should probably have everybody change their pg_hba.conf to trust. What do you think?

**Comment by begriffs** [comment]
@saicitus which install method did you use for your cluster? (i.e. is it all running on your local machine, is it spread across EC2 nodes, docker?)

When I followed the single machine cluster instructions on Ubuntu 14.04 the `pg_hba.conf` files for my master and workers were set to trust by default so this example had no problems.

**Comment by saicitus** [comment]
@begriffs I used production cluster method for ubuntu.
