### ISSUE TITLE
Summarize "choosing app type"

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#675]
## Communication goals (e.g. detailed howto vs orientation)

https://docs.citusdata.com/en/v7.4/develop/app_type.html still involves a lot of reading, despite prior simplification. Add an illustration or something at the top to help people quickly get the gist.

**Comment by sumedhpathak** [comment]
Hmm, the diagrams add a different and new way of representing MT vs RT, which we haven't used before. I don't know if it currently simplifies things. I was envisioning something similar to the table you used here:
https://github.com/citusdata/citus_docs/pull/699. There we talk about advantages, but can we classify use-case characteristics in similar quick bullet-points so users can quickly glance at that?
