### ISSUE TITLE
Add alternatives/workarounds for Unique Index on non-partition column.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#685]
See https://www.reddit.com/r/PostgreSQL/comments/8l04sy/have_any_of_you_migrated_from_postgresql_to_a/dzeagcg/

I had a few problems in Docs:
- Searching for "unique index" doesn't actually bring up anything meaningful.
https://docs.citusdata.com/en/v7.4/search.html?q=unique+index&check_keywords=yes&area=default
We should definitely add some content so that this search would be useful.

- We don't AFAICS have workarounds or options for unique index on non-partition column. Maybe this is in a separate section? @begriffs Do you know?

**Comment by begriffs** [comment]
We don't use the phrase unique index really. Instead the sections tend to say "unique constraint," or "uniqueness constraint."  You'll find more sections using those terms, but we could sprinkle in some other keywords for unique index to catch that search.

This issue might tie in with #504 as well, where that one talks about reference tables for cross-tenant uniqueness, and here we need to talk about including the distribution column in the unique index. It could be a general section about enforcing uniqueness both within and across tenants.
