### ISSUE TITLE
Document new connection configuration

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#694]
### Are there relevant blog posts or outside documentation about the concept/feature?

https://github.com/citusdata/citus/issues/2019

**Comment by begriffs** [comment]
@jasonmp85 can you fill in the details above once it's decided exactly what will change?

**Comment by jasonmp85** [comment]
@begriffs Most definitely; I'm now working on the separate pooling/direct connection/replication config (because @marcocitus mentioned wanting to have it decided sooner rather than later), so documenting it will help all involved.
