### ISSUE TITLE
Install instructions in older doc versions will install latest Citus

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#70]
Our Debian package cannot currently be pinned at a specific (older) version so we can't have the 5.0 docs' install instructions specify a way to get the version of the program they document.

We could
- Work on improving our Debian package structure (if it's possible) or
- Change the install instructions to tell the user that we no longer recommend installing the old version

**Comment by begriffs** [comment]
@jasonmp85 any opinion on this one?

**Comment by jasonmp85** [comment]
Not possible in PGDG, possible with packagecloud. I should have something for you in the near (weekish) future.

**Comment by begriffs** [comment]
Are we planning to switch to using packagecloud or should I close this issue?

**Comment by jasonmp85** [comment]
@sumedhpathak ? 😁

**Comment by sumedhpathak** [comment]
We have not discussed moving to package cloud, so its not on the horizon.

**Comment by jasonmp85** [comment]
Wait, so why does that mean we close this issue? It's still an issue, right (i.e. old instructions will install the latest Citus, not the old versions)?

I think this issue has to stay open until we decide whether this is a `WONTFIX` or something we will fix, just not yet (i.e. prioritize it).

**Comment by jasonmp85** [comment]
Didn't we make some progress on this issue recently? Or no?
