### ISSUE TITLE
Document how to paginate data from Citus tables 

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#74]
Citus currently doesn't support `LIMIT .. OFFSET` queries. We're looking to provide support for this in 5.2.

Still, for users who're looking to paginate through records, `LIMIT .. OFFSET` has certain shortcomings. We currently advise customers to use cursors to paginate through their end results; and we describe this in https://github.com/citusdata/citus/issues/394

@begriffs described methods to paginate in regular Postgres tables in [a blog post](https://www.citusdata.com/blog/1872-joe-nelson/409-five-ways-paginate-postgres-basic-exotic). Once we have `LIMIT .. OFFSET` implemented, we may want to add documentation on ways to paginate through records in distributed tables.

**Comment by begriffs** [comment]
We now have limit/offset support so this issue may be less pressing, unless there are special pagination considerations for a distributed db.
