### ISSUE TITLE
Note "grant usage" required for non-public schemas

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#765]
## Communication goals (e.g. detailed howto vs orientation)

In the Cloud section we talk about adding users and granting them access to tables. We should also add a note that "grant usage on ..." is required for schemas other than public.

### Good locations for content in docs structure

http://docs.citusdata.com/en/v7.5/cloud/security.html#users-and-permissions

**Comment by colton-citus** [comment]
Could we get this into the next docs release? It comes up a bit more often than I'd like
