### ISSUE TITLE
Update "How Far Can Citus Scale" section -- Reference to Kixer

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus_docs#790]
Could we update this section and replace Kixer with a different customer (who agreed to a case study with us)?

**Comment by ozgune** [comment]
I also realize that some of the references we give about scale is dated in this section. For example, Heap now stores ~900 TB of data. Do we want to update this section too?

**Comment by sumedhpathak** [comment]
@begriffs Can we prioritize this? Also, Mixrank has 1.6PB of data in their cluster. We could also reduce the number of stories we list here, since we also point to our customer stories section on our site.

**Comment by begriffs** [comment]
Yep, I moved it right under the 8.0 release checklist issue in waffle.
