### ISSUE TITLE
Document workaround for INSERT INTO (SELECT ...) from local to distributed table

### ISSUE THREAD

**Issue by umurc** [citusdata/citus_docs#80]
We have an issue open on INSERT INTO SELECT: https://github.com/citusdata/citus/issues/212
Can we use COPY from STDIN as a workaround to copy data from a local table to a distributed one?

**Comment by begriffs** [comment]
We both wrote this workaround in the workaround section and then removed it because of support in citus 6

**Comment by samay-sharma** [comment]
We have added support for INSERT / SELECT between distributed to distributed table. To COPY data from local to a distributed table still requires a workaround similar to what @umurc suggested.

**Comment by cmben** [comment]
I tried to copy data from one distributed table to another. Both are distributed by same column - **start_t**.
But i get following error -

`ERROR:  INSERT target table and the source relation of the SELECT partition column value must be colocated`

Query for reference - 
`INSERT INTO logs_columnwise SELECT * FROM logs_rowwise WHERE "start_t" > '2017-01-10';`

**Comment by sumedhpathak** [comment]
@cmben Could you post this question on either our Slack channel or citus-users google groups? You'll get a quicker response there. https://www.citusdata.com/about/contact_us. I suspect the filter clause doesn't restrict the source table (logs_rowwise) from only the shard on the same node.

**Comment by begriffs** [comment]
I think this issue may be fixed. Here's the experiment I did:

```sql
create table new_table ( like local_table );
select create_distributed_table('new_table', 'id');
insert into new_table select * from local_table;
-- succeeds
```
