### ISSUE TITLE
master_modify_multiple_shards() UDF

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus_docs#82]
We have a new function called `master_modify_multiple_shards`. This function takes a simple DELETE or UPDATE SQL query and runs it on worker shards.

```
SELECT master_modify_multiple_shards('DELETE FROM github_events WHERE event_id < 500');
SELECT master_modify_multiple_shards('UPDATE github_events SET event_public = FALSE WHERE event_type=''CreateEvent'' ');
```
One usage of this function can be deleting old data from hash tables. For append tables, we have `master_apply_delete_command` that drops the shards that its all rows satisfy the query conditions. `master_modify_multiple_shards` can be used with hash, range and append tables.

The distributed modifications in shards are done within a distributed transaction and the commit protocol can be changed by setting `citus.multi_shard_commit_protocol` to either `1pc` or `2pc`. The advantage of 2-Phase commit is that, it allows recovery from failures that occur during commits. 

1-Phase Commit works like this:
> Shard-1 Begin
> Shard-1 Query
> ...
> Shard-N Begin
> Shard-N Query
> Shard-1 Commit
> ...
> Shard-N Commit

With 2-Phase Commit, the actions are like the following:

> Shard-1 Begin
> Shard-1 Query
> ...
> Shard-N Begin
> Shard-N Query
> Shard-1 Prepare
> ...
> Shard-N Prepare
> Shard-1 Commit Prepared
> ...
> Shard-N Commit Prepared

### Notes:
- When the replication factor is more than one for any shards, the function takes exclusive locks on all shards. If you are sure that you are modifying old data and concurrent insert/update/deletes do not conflict each other (commutative), then setting citus.all_modifications_commutative to true can prevent exclusive locking and blocking other queries.

  A typical example in which you can use all_modifications_commutative is when you're removing old data:
```
SET citus.all_modifications_commutative TO on;
SELECT master_modify_multiple_shards('DELETE FROM events WHERE event_time < ''2016-01-01'' ');
``` 

  If all other modifications are inserts with event_time >= 2016-01-01 then it doesn't really matter in which order the delete is applied with respect to the inserts, so it's safe to mark the operation as commutative. 

- Commands on the placements are executed one by one, so a big update/delete might take a while. You should therefore avoid taking exclusive locks.
- The function does not mark shard placements as inactive, if it cannot connect to a node then it rolls everything back.
- For a short period (usually a few milliseconds), you might see data updated/deleted in one shard, but not yet in another shard, similar to COPY.

**Comment by begriffs** [comment]
Added docs for this function
