### ISSUE TITLE
GUCs to make citus_stat_statements more reliable

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#821]
## Why are we implementing it? (sales eng)

Internally citus_stat_statements joins information with pg_stat_statements. However the latter periodically removes old entries to save space. We ought to remove corresponding information from the former, but there is no mechanism to be notified exactly when to do this.

Mismatched data in {citus,pg}_stat_statements can make entries disappear and reappear in e.g. the list of top 10 queries.

## Communication goals (e.g. detailed howto vs orientation)

Example what mismatched stats will do, and then an explanation of citus_stats_statements retention controls.

### Good locations for content in docs structure

http://docs.citusdata.com/en/v8.0/admin_guide/cluster_management.html#viewing-query-statistics

## How does this work? (devs)

Two approaches:
1. Have the maintenance daemon periodically sync the citus and pg stats. The GUC `citus.stats_statements_purge_interval` sets time in seconds for the sync. A value of 0 disables periodic syncs.
2. Limit the number of entries we store. The `citus.stats_statements_max` GUC removes old entries when new ones cross the threshold. The default value is 50K, and the highest allowable value is 10M. Note that each entry costs about 140 bytes in shared memory so set the value wisely.

**Comment by mtuncer** [comment]
Regarding `How does this work?`

if there is more local (i.e. coordinator) query workload, it is advisable to to set `pg_stat_statements.max` to a larger value. Its default value is 5000, it could be increased to 10K, 20K or even 50K without much side effects. 

Beware that each change here requires restart of the postgresql service.

**Comment by mtuncer** [comment]
When I read 2 approaches, I felt like it meant 2 competing candidates. In fact, they are complementing each other since they address different parts of the visible problem
