### ISSUE TITLE
Coordinator->worker connection needs adjustment for 8.1 upgrade

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#827]
## Why are we implementing it? (sales eng)

The new version changes `citus.node_conninfo` from sslmode=prefer to sslmode=require when citus is compiled against a postgres with ssl compiled in.

This impacts new users onboarding to citus as well as existing users upgrading.

### Good locations for content in docs structure

Installation section: no change needed for pg10,11 but on pg9.6 the user is required to restart postgres as it can only enable ssl during boot.

Upgrade section: review the situation in linked PR that would cause people problems on upgrades. Reproduce the problem, verify that I can fix it, then update the docs.

### Link to relevant commits and regression tests if applicable

https://github.com/citusdata/citus/pull/2503

**Comment by begriffs** [comment]
Asked Jason and Marco for steps to reproduce SSL problems on upgrade.

**Comment by marcocitus** [comment]
We no longer support 9.6. We revert to sslmode=prefer for users who are upgrading and did not have ssl enabled yet. When adding new nodes to the cluster those nodes will have ssl enabled and sslmode=require. This mostly becomes relevant for inter-node communication (shard move, shard repair, re-partitioning)
