### ISSUE TITLE
Draining of nodes

### ISSUE THREAD

**Issue by JelteF** [citusdata/citus_docs#893]
## Why are we implementing it? (sales eng)

When removing a node from the cluster you have to take care, since there are shards on that node.
Draining of nodes is used to transfer all the shards to other nodes in the cluster, after which you can safely remove the node from the cluster.

### What are the typical use cases?

- Scaling down clusters
- Upgrading nodes to a bigger size and removing the smaller nodes

### Good locations for content in docs structure
1. `rebalance_table_shards`http://docs.citusdata.com/en/v8.3/develop/api_udf.html#rebalance-table-shards
   - [x] document new `drain_only` argument of 
   - [x] document that providing a table is not necessary (anymore), providing no table will rebalance all existing colocation groups.
2. http://docs.citusdata.com/en/v8.3/develop/api_udf.html#cluster-management-and-repair-functions
   - [x] document `master_drain_node` 
3. http://docs.citusdata.com/en/v8.3/develop/api_udf.html#metadata-configuration-information
   - [x] document `master_set_node_property`

## How does this work? (devs)

There's a new column `shouldhaveshards` in `pg_dist_node`. If it's false, but there are shards on the machine the rebalancer will move them away from there. 

### Example sql

There’s two flows of draining nodes that could be useful for you:
Remove multiple nodes:
1.	Run this for each node that you want to remove:
    ```sql
    SELECT * from master_set_node_property(node_hostname, node_port, 'shouldhaveshards', false);
    ```
2.	`SELECT * FROM rebalance_table_shards(drain_only := true);`
3.	Wait until it finishes
4.	Kill all the nodes

Remove  a single node (using usability UDF for single node case):
1.	`SELECT * from master_drain_node(node_hostname, node_port);`
2.	Wait until the command finishes
3.	Kill the node

### Are there relevant blog posts or outside documentation about the concept/feature?

No

### Link to relevant commits and regression tests if applicable

- PR: https://github.com/citusdata/citus-enterprise/pull/372
- regression tests: https://github.com/citusdata/citus-enterprise/pull/372/files#diff-b698af22c0ed49061162e6429e66df1bR490-R567

**Comment by jonels-msft** [comment]
Thank you for all the details!

**Comment by jonels-msft** [comment]
At first glance I thought `master_set_node_property` would be a general way to update `pg_dist_node` but it's hard coded to reject any property other than `shouldhaveshards`. That seems odd.

Also what's the interaction between `isactive` and `shouldhaveshards` in `pg_dist_node`? Should one of them imply the other?

**Comment by JelteF** [comment]
1. The idea is that it will be used for future properties that a user should be able to change. It might be good to change it such that you can also set "isactive" with it though. 

2. They are separate, but if isactive is false, the value of shouldhaveshards doesn't really matter.
