### ISSUE TITLE
Update trigger docs to use %L instead of %s

### ISSUE THREAD

**Issue by serprex** [citusdata/citus_docs#897]
https://github.com/citusdata/citus/issues/2354

The docs they're referring to:

https://github.com/citusdata/citus_docs/blob/85c1de3d92a73509c65361dece94400a5b5d272a/develop/reference_propagation.rst

https://github.com/citusdata/citus_docs/blob/85c1de3d92a73509c65361dece94400a5b5d272a/extra/triggers.rst

Marco's suggesting %L should be used over %s

**Comment by jonels-msft** [comment]
Thanks for this suggestion, I'll update and test the instructions in the next week or so.
