### ISSUE TITLE
(WIP) INSERT INTO ... SELECT ...; with repartitioning.

### ISSUE THREAD

**Issue by pykello** [citusdata/citus_docs#898]
## Why are we implementing it? (sales eng)

In short, this is an optimization. It doesn't enable anything we couldn't do before. The optimization is to in cases we don't need to do a merge step on coordinator, move data directly between nodes instead of routing them via coordinator.

More detailed description follows.

Before this, we had two ways to do "INSERT INTO target_table SELECT ...":

1. If the tasks of SELECT query were colocated with the shards of the target_table and the SELECT query didn't require any merge step on coordinator, we did a distributed INSERT/SELECT.

Not requiring merge step on coordinator means that all operations (filter, group by, ...) is pushed down to workers and all we need to do on coordinator is to fetch rows from workers. Examples of a SELECT query requiring merge step on coordinator is when the group by clause doesn't contain the distribution column. After fetching the rows from workers to coordinator, we need to do an extra GROUP BY on coordinator before returning results.

To check if a SELECT requires a merge step on coordinator, check its EXPLAIN output. If the top-level plan node is "Custom Scan (Citus Adaptive)", then it doesn't require a merge step on coordinator.

For example, if we have two colocated tables and we do "INSERT INTO target_table SELECT * FROM source_table", we can do this INSERT/SELECT in a distributed manner by executing tasks of form "INSERT INTO target_table_123456 SELECT * FROM source_table_2828289" directly on workers, where `target_table_123456` and `source_table_2828289` are shard tables which are colocated.

2. Pull results of SELECT to coordinator and then redirect rows to shards of the target table. If the SELECT query's tasks weren't colocated with target table or the SELECT query needed a merge step on the coordinator, then we used this method.

The new repartitioned INSERT/SELECT which was implemented in https://github.com/citusdata/citus/pull/3376 adds a 3rd method, which optimizes some cases of method 2. If the tasks of SELECT query are not colocated with the target table and the SELECT query doesn't require a merge step on the coordinator, we do:

1. Execute SELECT tasks and repartition their results so they match sharding scheme of target table
2. For each node pair, fetch partitions of SELECT results between them so all of the results that need to be insert into each shard of target table is colocated with it.
3. For each target shard, insert the now colocated partitions of SELECT results that matches its min/max ranges.

So this is just merely an optimization on INSERT/SELECT method 2. Instead of pulling rows to coordinator and then pushing them down to workers, we directly move the rows between workers.

### What are the typical use cases?

1. Changing distribution column of a table. Users can create a new table which has the same schema, but has a different distribution column. Then do `INSERT INTO new_table SELECT * FROM original_table`.
2. When they want to change the distribution columns value. We don't allow `UPDATE ... dist_column=...`. But they can do:

```sql
CREATE TABLE key_map(key_before int, key_after int);
SELECT create_reference_table('key_map');

CREATE TABLE dist_table_with_updated_keys (LIKE original_table);
SELECT create_distributed_table('dist_table_with_updated_keys', 'key');

INSERT INTO dist_table_with_updated_keys SELECT key_after, (rest of columns ...) FROM original_table INNER JOIN key_map ON key_map.key_before = original_table.key;
```

## Communication goals (e.g. detailed howto vs orientation)

To check what INSERT/SELECT method we are using, run an explain on the INSERT/SELECT statements.

For distributed INSERT/SELECTs, you will see a top level node of "Custom Scan (Citus Adaptive)", and worker task is an "Insert ..." task.

For repartitioned INSERT/SELECTs, you will see a top level node of "Custom Scan (Citus INSERT ... SELECT)", and it will specify "INSERT/SELECT method" as "repartition".

For example,

```
 Custom Scan (Citus INSERT ... SELECT)  (cost=0.00..0.00 rows=0 width=0)
   INSERT/SELECT method: repartition
   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0)
         Task Count: 4
         Tasks Shown: One of 4
         ->  Task
               Node: host=localhost port=5433 dbname=postgres
               ->  Seq Scan on source_table_102008 source_table  (cost=0.00..35.50 rows=25
50 width=4)
```

For pull to coordinator INSERT/SELECTs, you will see a top level node of "Custom Scan (Citus INSERT ... SELECT)", and it will specify "INSERT/SELECT method" as "pull to coordinator".

For example,

```
 Custom Scan (Citus INSERT ... SELECT)  (cost=0.00..0.00 rows=0 width=0)
   INSERT/SELECT method: pull to coordinator
   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0)
         Task Count: 4
         Tasks Shown: One of 4
         ->  Task
               Node: host=localhost port=5433 dbname=postgres
               ->  Seq Scan on source_table_102008 source_table  (cost=0.00..35.50 rows=25
50 width=4)
(8 rows)
```

If the new method causes a performance regression and you want to force a pull to coordinator INSERT/SELECT, you can disable repartitioned insert/selects by:

```
set citus.enable_repartitioned_insert_select to off;
```

Another reason you might want to disable this feature is if worker nodes cannot see each other and there is only coordinator to worker connections.

### Good locations for content in docs structure

In most cases, users shouldn't care about this. Maybe a section in "SQL reference" -> "Ingesting, Modifying Data".

The `citus.enable_repartitioned_insert_select` flag is hidden. I am not sure what is our policy for hidden flags. Do we document them or do we only communicate them to users for trouble-shooting?

## How does this work? (devs)

First, it runs `worker_partition_query_result()` for all tasks of the SELECT query, which creates result files for each {select task}/{target table shard} pair. The results files are named as "repartitioned_results_{job id}_from_{source shard id}_to_{target shard index}.dat".

In the next step, we move result files between nodes using at most one call of `fetch_intermediate_results()` between each node pair.

In the final step, we insert into the shards of the target table using "INSERT INTO target_table_123456 SELECT * FROM read_intermediate_results(... list of result files to be inserted into the shard ...);".

If you set client_min_messages to DEBUG2, you should see the final "INSERT INTO ... read_intermediate_results(...)" statements.

### Example sql

(TODO)

### Corner cases, gotchas

Other than what was explained previously:

1. This is not expected to perform well if the target table has a lot of shards. This is because the `worker_partition_query_result()` call takes arrays of min/max values of shard intervals so it can decide how to partition task results. If these arrays are huge, overhead of creating/deparsing/shipping/parsing of these arrays will be huge. In these cases, either use pull to coordinator insert/select, or make target table a partitioned table so each partition has relatively smaller number of shards.

2. We don't use repartitioned insert select if the SELECT query requires repartitioned joins.

### Are there relevant blog posts or outside documentation about the concept/feature?

No

### Link to relevant commits and regression tests if applicable

PR: https://github.com/citusdata/citus/pull/3376
Regression tests: https://github.com/citusdata/citus/blob/master/src/test/regress/expected/insert_select_repartition.out

**Comment by jonels-msft** [comment]
> If the tasks of SELECT query are not colocated with the target table and the SELECT query doesn't require a merge step on the coordinator

@pykello can you give me a rough guideline of which sql features would cause a merge step on the coordinator? I'd like to include that in the DML reference to help people predict whether the insert…select will get the rebalancer optimization.

**Comment by pykello** [comment]
@jonels-msft 

1. GROUP BY when distribution column is not part of the group key.
2. ORDER BY
3. LIMIT
4. OFFSET
5. Window functions
6. Joins between non-colocated tables (i.e. repartition joins)

**Comment by marcocitus** [comment]
Minor note: Window functions can be used in re-partitioning if they "partition by" the distribution column of the source table(s).
