### ISSUE TITLE
Cloud Formation creation shows description as Citus 5.0

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus_docs#90]
Lauch a Citus cluster using [Cloud Formation Template](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=Citus&templateURL=https:%2F%2Fcitus-deployment.s3.amazonaws.com%2Faws%2Fcitus5%2Fcloudformation%2Fcitus5.json).

The **description** has Citus 5.0.
**Regarding installation:** Citus 5.1 is getting installed. (because it is picked up from the latest pgdg repo)

Just dropping a note, due to this issue, a citus user(on support@/engage@) using the cloud formation template, mentioned that he was using Citus 5.0, but realized that he was using Citus 5.1 (because he was running \copy for append)

Here goes the pic:
![image](https://cloud.githubusercontent.com/assets/18174230/16016426/dd5dca46-314f-11e6-9ac5-511738adcd11.png)

**Comment by begriffs** [comment]
Verified it now says "Citus 6.0"
