### ISSUE TITLE
Rebalance strategies

### ISSUE THREAD

**Issue by JelteF** [citusdata/citus_docs#900]
## Why are we implementing it? (sales eng)

For some customers the rebalancing that we do by default is far from optimal. With default rebalancing we make a couple of assumptions:
1. shards are roughly the same size
2. shards get roughly the same amount of traffic
3. worker nodes are all the same size/type
4. there is no dedicated node for a shard

If any of these don't hold the default rebalancing can result in a bad plan.

### What are the typical use cases?

1. Rebalancing by disk size is especially useful for SaaS apps that shard by tenant_id. Often these apps have a couple of big customers that cause the shards that these customers are on to be much bigger than others. In that case it can make more sense to rebalance by disk size, than by shard count.
2. Pinning of a shard to a specific node can be for any cluster that has a hot shard. For example a shard containing a high traffic customer in a SaaS app. All other shards can be kept of the node where this shard resides. This way you reduce the noisy neighbour problem. This way the shard rebalancer won't move them there.

### Good locations for content in docs structure

1. http://docs.citusdata.com/en/v9.1/develop/api_udf.html#rebalance-table-shards
   - [ ] document new `rebalance_strategy` argument
2. http://docs.citusdata.com/en/v9.1/develop/api_udf.html#master-drain-node
   - [ ] document new `rebalance_strategy` argument
3. http://docs.citusdata.com/en/v8.3/develop/api_udf.html#cluster-management-and-repair-functions
   - [ ] document `get_rebalance_table_shards_plan`, basically a dry run version of `rebalalance_table_shards`. 
   - [ ] document the `citus_add_rebalance_strategy` UDF and the matching `pg_dist_rebalance_strategy` table  (the rebalance strategies are stored there).
   - [ ] document the `citus_set_default_rebalance_strategy` UDF

## How does this work? (devs)

The algorithm takes 4 input:
- function for cost of a shard
- function for capacity of a node
- function for if a shard is allowed on a node
- threshold

With these inputs the algorithm can determine:
1. the utilization of a node: `cost of all shards on the node/capacity of the node`
2. `average_utilization`: `sum(costs of shards)/sum(capacities of the nodes)`
3. `utilization_upper_bound`: `(1.0 + threshold) * average_utilization`
4. `utilization_lower_bound`: `(1.0 - threshold) * average_utilization`

The rebalancing algorthm tries to do two things:
1. Move all shards to a node that they are allowed to be on
2. Get the utilization for each node between `utilization_upper_bound` and `utilization_lower_bound`
   

### Example sql

Shard isolation, isolating shard 10000 on node with IP '10.0.0.1':
```sql
CREATE FUNCTION isolate_shard_10000_on_10_0_0_1(shardid bigint, nodeidarg int)
    RETURNS boolean AS $$
    SELECT
        (CASE WHEN nodename = '10.0.0.1' THEN shardid = 10000 ELSE shardid != 10000 END)
    FROM pg_dist_node where nodeid = nodeidarg
    $$ LANGUAGE sql;

-- The next two definitions are recommended in combination with the above function.
-- This way the average utilization of nodes is not impacted by the isolated shard.
CREATE FUNCTION no_capacity_for_10_0_0_1(nodeidarg int)
    RETURNS real AS $$
    SELECT
        (CASE WHEN nodename = '10.0.0.1' THEN 0 ELSE 1 END)::real
    FROM pg_dist_node where nodeid = nodeidarg
    $$ LANGUAGE sql;
CREATE FUNCTION no_cost_for_10000(shardid bigint)
    RETURNS real AS $$
    SELECT
        (CASE WHEN shardid = 10000 THEN 0 ELSE 1 END)::real
    $$ LANGUAGE sql;
-- Add the strategy
SELECT citus_add_rebalance_strategy(
        'isolating_10000',
        'no_cost_for_10000',
        'no_capacity_for_10_0_0_1',
        'isolate_shard_10000_on_10_0_0_1',
        0
    );
-- Preview moves using new strategy
SELECT * FROM get_rebalance_table_shards_plan(rebalance_strategy := 'isolating_10000');
-- Use the strategy to rebalance
SELECT rebalance_table_shards(rebalance_strategy := 'isolating_10000');
```

Different node capacity for nodes with specific hostname:
```sql
CREATE FUNCTION v2_node_double_capacity(nodeidarg int)
    RETURNS boolean AS $$
    SELECT
        (CASE WHEN nodename LIKE '%.v2.worker.citusdata.com' THEN 2 ELSE 1 END)
    FROM pg_dist_node where nodeid = nodeidarg
    $$ LANGUAGE sql;
```

Using `citus_stat_statements` it's possible to rebalance by number of queries that go to a shard (requires putting `pg_stat_statements` in `shared_preload_libraries`):
```sql
CREATE FUNCTION cost_of_shard_by_number_of_queries(shardid bigint)
    RETURNS real AS $$
    SELECT coalesce(sum(calls)::real, 0.001) as shard_total_queries
    FROM citus_stat_statements
    WHERE partition_key is not null
        AND get_shard_id_for_distribution_column('tab', partition_key) = shardid;
$$ LANGUAGE sql;


-- Add the strategy
SELECT citus_add_rebalance_strategy(
        'by_query_count',
        'cost_of_shard_by_number_of_queries',
        'citus_node_capacity_1',
        'citus_shard_allowed_on_node_true',
        0.1
    );

-- Preview moves using new strategy
SELECT * FROM get_rebalance_table_shards_plan(rebalance_strategy := 'by_query_count');

-- Use the strategy to rebalance
SELECT rebalance_table_shards(rebalance_strategy := 'by_query_count');
```

### Corner cases, gotchas

1. If you have the number of shards tuned to the number of cores to make the most of parallelism in Citus, then the `by_disk_size` strategy is likely not a good choice.

2. It's a new feature and it's possible that the planning can result in a strange/suboptimal plan in some cases. When using another strategy than the default `by_shard_count` strategy, always take a look at the plan generated by `get_rebalance_table_shards_plan` first before executing the moves. If you run into issues strange/suboptimal plans it can be good to contact support about it, so we can possibly change the algorithm to support these cases.

3. `get_rebalance_table_shards_plan` can output a slightly different plan than what a `rebalance_table_shards` call with the same arguments will do, because they are not executed at the same time. So, e.g. the disk size might have changed just over a cutoff point. This is not very likely though.

4. If using `by_disk_size` rebalancing you should not use a threshold of 0. Otherwise it's possible that a shard is only moved because disk usage decreases by a few mega bytes.

5. As described above if you are not careful, shard isolation influences utilization calculation for the other nodes. You can work around this by setting the cost of the shard that you isolate to 0, as well as setting the capacity of the node that you isolate it on to 0.

### Are there relevant blog posts or outside documentation about the concept/feature?

This can be combined with the Citus landlord feature (`citus_stat_statements`) to make a cost function for shards based on query time: https://www.citusdata.com/blog/2018/07/31/introducing-landlord-per-tenant-stats/

### Link to relevant commits and regression tests if applicable

PR: https://github.com/citusdata/citus-enterprise/pull/373
tests: https://github.com/citusdata/citus-enterprise/pull/373/files#diff-b698af22c0ed49061162e6429e66df1bR613-R797

**Comment by jonels-msft** [comment]
Thanks for the comprehensive, detailed issue!

**Comment by JelteF** [comment]
No problem. It's somewhat complex feature that requires a decent understanding to use correctly. I will go over it tomorrow again to see if I forgot something. And maybe add a little example for `citus_stat_statements`.

**Comment by saicitus** [comment]
@JelteF  @jonels-msft  I assume that this section `How does this work? (devs)` will not be in the actual documentation, just that it seems complex to understand for the end user? High level summary of rebalance_strategy and it's parameters should be enough. Also a couple examples of usage would help.

**Comment by JelteF** [comment]
@saicitus I was unsure on the amount of detail we wanted there, so I definitely erred on the side of too much detail. I do think it's important to explain what the different arguments in `citus_add_rebalance_strategy` are for though.

**Comment by jonels-msft** [comment]
Completed.
