### ISSUE TITLE
CTE Pushdown in Citus 9.2

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus_docs#901]
## Why are we implementing it? (sales eng)

Before Citus 9.2, all the CTEs are executed through pull-push execution. That adds considerable amount of unnecessary execution times.

In some (or many?) cases, some or all of the CTEs in the query can be pushed down similar to how subqueries are pushed down. This could give a huge boost in performance.

### What are the typical use cases?

This is only valid for multi-shard queries, so we should probably explicitly mention that. In any way, the router queries are always pushed down, so it is not a concern.

The CTE pushdown is most useful in real-time analytics use-case, where CTEs and joins between CTEs/distributed tables follows the rules for (sub)query pushdown.
1) Tables should be colocated
2) The CTE queries should not require any merge steps (e.g., LIMIT or GROUP BY on non-distribution key)
3) Tables and CTEs should be joined on distribution keys 

As long as the above conditions are hold, the CTE is going to be pushed down. In case the CTE does not fit into the above rules, the CTE is executed via pull-push execution as it used to be. So, it is possible to have some CTEs are pushed down whereas some are pulled-pushed.

### Good locations for content in docs structure

I think we should do two things.

First, in our docs, we explicitly or implicitly mention that all CTEs are going to use pull-push execution. That's not true anymore, pushdownable CTEs are going to be pushed down. We should find such reference and somehow relax that assumption.

Second, we might consider explicitly mentioning about CTE pushdown here: http://docs.citusdata.com/en/v9.1/sharding/data_modeling.html#co-location-means-better-feature-support 

We might consider having a separate section on this, please see  `Corner cases, gotchas` section where we need to mention about the limitations.

## How does this work? (devs)

Applicable CTEs are inlined as subqueries, and subquery optimizations are applied. This enables CTE pushdown. So, they are not actually pushed down as CTEs, but inlined as subqueries. See below for more details.

### Example sql

There are 3 cases. Common setup SQL

```SQL
CREATE TABLE users_table (user_id int, time timestamp, value_1 int, value_2 int, value_3 float, value_4 bigint);
SELECT create_distributed_table('users_table', 'user_id');

CREATE TABLE events_table (user_id int, time timestamp, event_type int, value_2 int, value_3 float, value_4 bigint);
SELECT create_distributed_table('events_table', 'user_id');



INSERT INTO users_table SELECT (i * random())::int % 10000, timestamp '2014-01-10 20:00:00' +
       random() * (timestamp '2014-01-20 20:00:00' -
                   timestamp '2014-01-10 10:00:00'),(i * random())::int % 10000, (i * random())::int % 10000, (i * random())::int % 10000 FROM generate_series(0, 1000000) i;


INSERT INTO events_table SELECT (i * random())::int % 10000, timestamp '2014-01-10 20:00:00' +
       random() * (timestamp '2014-01-20 20:00:00' -
                   timestamp '2014-01-10 10:00:00'),(i * random())::int % 10000, (i * random())::int % 10000, (i * random())::int % 10000 FROM generate_series(0, 1000000) i;

```

####  1) Case 1: Everything is pushdown-able. Both CTEs are colocated, joined on distribution key. Plus, the queries in CTEs doesn't have that require merge step (LIMIT, OFFSET or GROUP BY on non-distribution key etc)
```SQL
WITH first_pushdownable_cte AS
(
	 SELECT user_id, max(value_1) as max FROM users_table GROUP BY user_id
),
second_pushdownable_cte AS
(
	SELECT user_id, max(value_2) as max FROM events_table GROUP BY user_id
)
SELECT count(*) FROM first_pushdownable_cte JOIN second_pushdownable_cte USING (user_id, max);
```

This is what we send to workers: 
```SQL
SELECT count(*) AS count FROM (SELECT FROM ((SELECT users_table.user_id, max(users_table.value_1) AS max FROM public.users_table_102542 users_table GROUP BY users_table.user_id) first_pushdownable_cte JOIN (SELECT events_table.user_id, max(events_table.value_2) AS max FROM public.events_table_102550 events_table GROUP BY events_table.user_id) second_pushdownable_cte USING (user_id, max))) worker_subquery
```

#### 2) Case 2: The first CTE is still pushdown-able, but the second one is not because it is not joined on distribution key with the first CTE

```SQL
WITH first_pushdownable_cte AS
(
	 SELECT user_id, max(value_1) as max FROM users_table GROUP BY user_id
),
second_non_pushdownable_cte AS
(
	SELECT user_id, max(value_2) as max FROM events_table GROUP BY user_id
)
SELECT count(*) FROM first_pushdownable_cte JOIN second_non_pushdownable_cte USING (max) WHERE first_pushdownable_cte.user_id != second_non_pushdownable_cte.max;
```

This is what we send to workers: 
```SQL
SELECT count(*) AS count FROM (SELECT FROM ((SELECT users_table.user_id, max(users_table.value_1) AS max FROM public.users_table_102542 users_table GROUP BY users_table.user_id) first_non_pushdownable_cte JOIN (SELECT intermediate_result.user_id, intermediate_result.max FROM read_intermediate_result('224_1'::text, 'binary'::citus_copy_format) intermediate_result(user_id integer, max integer)) second_non_pushdownable_cte USING (max)) WHERE (first_non_pushdownable_cte.user_id OPERATOR(pg_catalog.<>) second_non_pushdownable_cte.max)) worker_subquery
```

#### 3) Case 3: None of the CTEs are pushdown-able as they have GROUP BY on non-dist key.

```SQL
WITH first_non_pushdownable_cte AS
(
	 SELECT max(user_id) as max FROM users_table GROUP BY value_1
),
second_non_pushdownable_cte AS
(
	SELECT max(user_id) as max FROM events_table GROUP BY value_2
)
SELECT count(DISTINCT first_non_pushdownable_cte.max) FROM first_non_pushdownable_cte JOIN second_non_pushdownable_cte USING (max) WHERE first_non_pushdownable_cte.max = second_non_pushdownable_cte.max;

```

So, the final query has only intermediate results. This is how it used to work for all CTEs:
```SQL
SELECT count(DISTINCT first_non_pushdownable_cte.max) AS count FROM ((SELECT intermediate_result.max FROM read_intermediate_result('239_1'::text, 'binary'::citus_copy_format) intermediate_result(max integer)) first_non_pushdownable_cte JOIN (SELECT intermediate_result.max FROM read_intermediate_result('239_2'::text, 'binary'::citus_copy_format) intermediate_result(max integer)) second_non_pushdownable_cte USING (max)) WHERE (first_non_pushdownable_cte.max OPERATOR(pg_catalog.=) second_non_pushdownable_cte.max)
```

#### 1) Postgres version 
- This feature is only avaliable in PG 12. Some background: Before PostgreSQL 12, CTEs are considered to be optimization fences on Postgres (and also in Citus). However, in PostgreSQL 12, postgres hackers implemented a feature called [`CTE inlining`](https://www.depesz.com/2019/02/19/waiting-for-postgresql-12-allow-user-control-of-cte-materialization-and-change-the-default-behavior/). In simple words, convert CTEs into subqueries, so that they can benefit from many optimizations that Postgres implements for subqueries.

This approach inspired us since Citus was doing the same. We've a very optimized way of planning subqueries, but not CTEs. So, when Postgres 12 is avaliable, Citus applies the same optimizations as Postgres (a.k.a., inlines CTEs) to apply the optimizations for subqueries.

**Thus, this feature is mostly useful in Postgres 12**.  There are few cases that Citus can benefit from this feature in Postgres 11. But, since they are very limiting, I'd suggest us to position this feature only avaliable on Postgres 12, by referring to CTE inlining in Postgres 12.

#### 2) Controlling CTE inlining:

Citus obeys the `MATERIALIZED` and `NOT MATERIALIZED` keywords as in **[Postgres](https://www.postgresql.org/docs/12/queries-with.html)**.  On Citus jargon, `MATERIALIZED` means pull-push execution, `NOT MATERIALIZED` means try to inline if possible. 

If none is specified, the default action is that, as in Postgres, if the CTE is referenced only once, do `NOT MATERIALIZED`. Else, use `MATERIALIZED` as executing the same CTE twice might be expensive.

On citus, since we support Postgres 11, we have another GUC to control the cte inlining. Users can simply disable all CTE inlining with `set citus.enable_cte_inlining TO false;`. We don't need to expose this GUC to users, sharing as a reference mostly.

### Are there relevant blog posts or outside documentation about the concept/feature?

- On postgres side, if you search for `CTE Inlining`, you'd find lots of information. Though, I don't know if this item asks for it or not. 

### Link to relevant commits and regression tests if applicable

The commits are meant to be self-contained, so could be useful to understand what is going on: https://github.com/citusdata/citus/pull/3161

**Comment by jonels-msft** [comment]
Thank you for the thorough description.

**Comment by jonels-msft** [comment]
Note to self: relates to https://github.com/citusdata/citus_docs/issues/664

**Comment by jonels-msft** [comment]
@onderkalaci we say in our [workarounds page](http://docs.citusdata.com/en/v9.2/develop/reference_workarounds.html) that recursive CTEs work in single-shard queries only. Is this still true?

**Comment by jonels-msft** [comment]
Also do we have an updated example we want to share in [Subquery/CTE Network Overhead](http://docs.citusdata.com/en/v9.2/performance/performance_tuning.html#subquery-cte-network-overhead)? When I try the version with cte_slow it actually goes slightly faster than cte_fast, but with a small planning overhead:

```
> explain analyze WITH cte_slow AS (SELECT * FROM page_views)
SELECT * FROM cte_slow LIMIT 10;
                                                                        QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.00..0.00 rows=0 width=0) (actual time=13.677..13.679 rows=10 loops=1)
   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=13.676..13.677 rows=10 loops=1)
         Task Count: 32
         Tasks Shown: One of 32
         ->  Task
               Node: host=10.0.0.249 port=5432 dbname=citus
               ->  Limit  (cost=0.00..0.16 rows=10 width=23) (actual time=0.026..0.028 rows=10 loops=1)
                     ->  Seq Scan on page_views_102008 page_views  (cost=0.00..53321.27 rows=3257327 width=23) (actual time=0.025..0.026 rows=10 loops=1)
                   Planning Time: 0.074 ms
                   Execution Time: 0.047 ms
 Planning Time: 0.864 ms
 Execution Time: 13.699 ms
(12 rows)
```

```
> explain analyze WITH cte_fast AS (SELECT * FROM page_views limit 10)
SELECT * FROM cte_fast LIMIT 10;
                                                                              QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=13.613..13.614 rows=10 loops=1)
   ->  Distributed Subplan 29_1
         ->  Limit  (cost=0.00..0.00 rows=0 width=0) (actual time=16.118..16.133 rows=10 loops=1)
               ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=16.117..16.118 rows=10 loops=1)
                     Task Count: 32
                     Tasks Shown: One of 32
                     ->  Task
                           Node: host=10.0.0.249 port=5432 dbname=citus
                           ->  Limit  (cost=0.00..0.16 rows=10 width=23) (actual time=0.009..0.011 rows=10 loops=1)
                                 ->  Seq Scan on page_views_102008 page_views  (cost=0.00..53321.27 rows=3257327 width=23) (actual time=0.009..0.010 rows=10 loops=1)
                               Planning Time: 0.113 ms
                               Execution Time: 0.024 ms
         Planning Time: 0.000 ms
         Execution Time: 16.157 ms
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=5432 dbname=citus
         ->  Limit  (cost=0.00..0.11 rows=6 width=48) (actual time=0.047..0.049 rows=10 loops=1)
               ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..0.11 rows=6 width=48) (actual time=0.046..0.047 rows=10 loops=1)
             Planning Time: 0.054 ms
             Execution Time: 0.064 ms
 Planning Time: 0.683 ms
 Execution Time: 13.630 ms
(24 rows)
```

**Comment by onderkalaci** [comment]
> @onderkalaci we say in our workarounds page and faq that recursive CTEs work only in single-shard queries. Is this still true?

Yes, that is still true.

> Also do we have an updated example we want to share in Subquery/CTE Network Overhead? When I try the version with cte_slow it actually goes slightly faster than cte_fast, but with a small planning overhead:

Good point, `cte_slow` now is inlined as subquery and become pushdownable, so doesn't require pull-push execution.

`cte_fast` is also inlined as subquery, but since the subquery is not pushdownable because of `LIMIT`, we do pull-push execution for the subquery.  That's why I'd expect `cte_fast` to be slower now :)

I've been  thinking about finding a new `cte_slow` and `cte_fast`, but it is not easy to find  those type of very straight-forward queries. So, instead of writing complex/unusual queries, I'd suggest we remove `cte_fast` / `cte_slow` examples. I don't want to write examples which requires extensive planner understanding (or users might ask why Citus cannot optimize these queries).
