### ISSUE TITLE
(WIP) How to set up SSL/TLS when running a self hosted Citus

### ISSUE THREAD

**Issue by JelteF** [citusdata/citus_docs#909]
## Why are we implementing it? (sales eng)

Requirement from security compliance team within Microsoft

## Communication goals (e.g. detailed howto vs orientation)

1. What does Citus do by default? A: for new clusters self-signed certificates, for old clusters no encryption by default
2. Why are self-signed certificates not secure (and thus also the Citus default)? A: MITM attack is still easily possible
3. What does a user need to do to get `ssl=verify-full` working? A: Get certificates from a CA (either company internal PKI or publicly trusted). Install those certificates. Manage key rotation. Do this for all nodes in the cluster.
4. Mention `hostssl` for denying unencrypted connections 

### Are there relevant blog posts or outside documentation about the concept/feature?
Postgres docs on setting up SSL/TLS
pg_auto_failover docs on this same topic:
https://github.com/citusdata/pg_auto_failover/blob/release-1.2/docs/security.rst

**Comment by jonels-msft** [comment]
Due before April 1
