### ISSUE TITLE
inter-region vpc peering in citus cloud is not supported

### ISSUE THREAD

**Issue by kileri** [citusdata/citus_docs#944]
Docs should raise the caveat that vpc peering is only supported with same region vpcs for clarity to customers. Depending on how we decide to handle [the inter-region vpc peering](https://github.com/citusdata/cloudplane/issues/1538) we may need to change again.

**Comment by jonels-msft** [comment]
Thanks for reporting. Would you like to open a quick PR to add the caveat?
