### ISSUE TITLE
Issue with view that utilises "union all"

### ISSUE THREAD

**Issue by MathiasVersichele** [citusdata/citus_docs#954]
I'm having lots of trouble with views that utilise "union all". This is the view:

```
CREATE OR REPLACE VIEW rvpezocoav as
SELECT rtpezocoav.id,
    rtpezocoav.ad_id,
    rtpezocoav.pe_id,
    rtpezocoav.zo_id,
    rtpezocoav.co_id,
    rtpezocoav.value_num,
    rtpezocoav.value_text
   FROM rtpezocoav
     JOIN rmv_active_peco act ON act.co_id = rtpezocoav.co_id AND act.pe_id = rtpezocoav.pe_id
UNION ALL
 SELECT av.id,
    av.ad_id,
    rtpe.id AS pe_id,
    av.zo_id,
    av.co_id,
    av.value_num,
    av.value_text
   FROM rtpezocoav av
     JOIN rtpe ON av.pe_id = rtpe.baseline_id
     JOIN rmv_active_peco act ON act.co_id = av.co_id AND act.pe_id = rtpe.id
  WHERE NOT (EXISTS ( SELECT 1
           FROM rtpezocoav av_1
          WHERE av_1.pe_id = rtpe.id AND av_1.zo_id = av.zo_id AND av_1.co_id = av.co_id AND av_1.ad_id = av.ad_id))
```

- rtpezocoav is a distributed table on zo_id
- rmv_active_peco & rtpe are reference tables

The following query fails after a while with the 'intermediate result size exceeds citus.max_intermediate_result_size (currently 1048576 kB)':
```
select count(1) from rvpezocoav where pe_id = 391;
```

I have no idea why we would need to reshuffle data as it's a join between one distributed table and two reference tables.

What I tried and didn't work:
- remove join with rmv_active_peco
- remove where not (exists ...) clause

Only thing that works is changing the union ALL to just a union. No idea why that makes a difference...

But then I end up with the next problem:

```
select count(1)
	from rvpezocoav pezoco
	join rtco co on pezoco.co_id = co.lo_id
	where ad_id = 4
	        and pe_id = 391
	        and lo_id = 505
```
fails with ERROR: complex joins are only supported when all distributed tables are co-located and joined on their distribution columns.

rtco here is also a reference table.

What I tried according to suggestions on slack:

```
 CREATE OR REPLACE VIEW rvpezocoav as
				select * from 
				(
				select * from 
				(
				SELECT rtpezocoav.id,
				    rtpezocoav.ad_id,
				    rtpezocoav.pe_id,
				    rtpezocoav.zo_id,
				    rtpezocoav.co_id,
				    rtpezocoav.value_num,
				    rtpezocoav.value_text
				   FROM rtpezocoav
				     JOIN rmv_active_peco act ON act.co_id = rtpezocoav.co_id AND act.pe_id = rtpezocoav.pe_id
				     offset 0
				    ) as z1
				UNION --ALL  --!!!!!
				 select * from 
				 (
					SELECT av.id,
				    av.ad_id,
				    rtpe.id AS pe_id,
				    av.zo_id,
				    av.co_id,
				    av.value_num,
				    av.value_text
				   FROM rtpezocoav av
				     JOIN rtpe ON av.pe_id = rtpe.baseline_id
				     JOIN rmv_active_peco act ON act.co_id = av.co_id AND act.pe_id = rtpe.id
				  WHERE NOT (EXISTS ( SELECT 1
				           FROM rtpezocoav av_1
				          WHERE av_1.pe_id = rtpe.id AND av_1.zo_id = av.zo_id AND av_1.co_id = av.co_id AND av_1.ad_id = av.ad_id))
				          offset 0
				      ) as z2
				  ) as z;
```

This brings me back to the original problem: ERROR: the intermediate result size exceeds citus.max_intermediate_result_size (currently 1048576 kB)

I've been going in circles trying to make this work for the last few days... This is a real showstopper for us unfortunately.

**Comment by jonels-msft** [comment]
Thanks for reporting. Let's close this issue and continue the conversation in https://github.com/citusdata/citus/issues/4144
