### ISSUE TITLE
Some workarounds are not needed anymore

### ISSUE THREAD

**Issue by naisila** [citusdata/citus_docs#978]
What was before an unsupported feature and had a workaround, is now a supported feature. For example, joining local and distributed tables.

For joining a local and distributed table, we only lack support for correlated subqueries
```SQL
SELECT (SELECT count(*) FROM local WHERE dist.x = local.x) FROM dist;
```
The workaround sections needs updating
https://docs.citusdata.com/en/latest/develop/reference_workarounds.html#workarounds

**Comment by jonels-msft** [comment]
Part of this has been fixed by https://github.com/citusdata/citus_docs/pull/977 but we still don't mention the correlated subqueries part.

**Comment by naisila** [comment]
Yes. Previously in the _Common Error Messages_ part, we were suggesting to do the workaround, now we simply suggest upgrading Citus (like in other parts of _Common Error Messages_ sections).

I didn't want to mention the correlated subqueries there since it is a specific case, considering we support the normal join.

However, depending on how we update the _Workarounds_ section, we may link it again in the resolution part of _Relation foo is not distributed_ subsection.

**Comment by naisila** [comment]
@onurctirtir @jonels-msft changing a distribution column also doesn't need a workaround anymore, so I believe that subsection should be removed as well. Please consider that before closing this issue.

```SQL
SELECT alter_distributed_table('dist_table', distribution_column := 'desired_column');
```

**Comment by jonels-msft** [comment]
Thanks for the note.

@halilozanakgul will be documenting alter_distributed_table, and can update the workarounds section as part of his PR.
