### ISSUE TITLE
Multi-Node Guide for Ubuntu or Debian has wrong function call

### ISSUE THREAD

**Issue by lancewl** [citusdata/citus_docs#999]
https://docs.citusdata.com/en/stable/installation/multi_node_debian.html

In the 2. Verify that installation has succeeded section:
`sudo -i -u postgres psql -c "SELECT * FROM citus_get_active_worker_nodes();"`
throws error: `ERROR:  function citus_get_active_worker_nodes() does not exist`

I changed it to `master_get_active_worker_nodes()` and it works.

**Comment by hanefi** [comment]
I guess you installed an earlier version of Citus. Please make sure you are using the correct version of the docs.

We deprecated most of the user facing `master_*` UDFs in several parts. This particular UDF is renamed in https://github.com/citusdata/citus/pull/4830 and shipped it in 10.1 release.

They are still there for backward compatibility, however we suggest the users to use `citus_*` UDFs instead, if they are renamed.
